### ISSUE TITLE
Typing invalid IRI into Default dataset throws

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1093]
**Describe the bug**
When using an invalid IRI for "Default dataset" in the "New Knowledge Base Wizard", it throws an uncatched exception.

**To Reproduce**
1. Create a new KB
2. Enter an invalid IRI for "Default dataset"
3. See error in log
**Expected behavior**
No error

**Screenshots**

**Please complete the following information:**
 - Version and build ID: 0.9.0 dbc3ccb6c095d2291c9478c4f14044526c0b8b06
 - OS: Linux
 - Browser: Chrome

**Comment by reckart** [comment]
Probably applies only to the 0.8.x branch.

**Comment by reckart** [comment]
Problem exists in 0.8.3-SNAPSHOT (2019-04-04 20:24:21, build f7a7cb116c5ce51eab5b1da694df931e0476190e) as well:

```
^[OF2019-04-05 08:57:28 ERROR [rec] KnowledgeBasePage - Error: null
java.lang.NullPointerException: null
	at org.cyberborean.rdfbeans.datatype.DefaultDatatypeMapper.getRDFValue(DefaultDatatypeMapper.java:114) ~[rdfbeans-2.2.jar!/:?]
	at de.tudarmstadt.ukp.inception.kb.InceptionValueMapper.mapValue(InceptionValueMapper.java:66) ~[inception-kb-0.8.3-SNAPSHOT.jar!/:?]
	at de.tudarmstadt.ukp.inception.kb.InceptionValueMapper.mapStatementValue(InceptionValueMapper.java:40) ~[inception-kb-0.8.3-SNAPSHOT.jar!/:?]
	at de.tudarmstadt.ukp.inception.kb.reification.NoReification.reify(NoReification.java:76) ~[inception-kb-0.8.3-SNAPSHOT.jar!/:?]
	at de.tudarmstadt.ukp.inception.kb.reification.NoReification.lambda$upsertStatement$2(NoReification.java:232) ~[inception-kb-0.8.3-SNAPSHOT.jar!/:?]
	at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl.update(KnowledgeBaseServiceImpl.java:833) ~[inception-kb-0.8.3-SNAPSHOT.jar!/:?]
	at de.tudarmstadt.ukp.inception.kb.reification.NoReification.upsertStatement(NoReification.java:228) ~[inception-kb-0.8.3-SNAPSHOT.jar!/:?]
	at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl.upsertStatement(KnowledgeBaseServiceImpl.java:772) ~[inception-kb-0.8.3-SNAPSHOT.jar!/:?]
...
```

This appears to be the same trace as in #1093 - so potentially a duplicate issue.

**Comment by reckart** [comment]
The default dataset field does not yet exist in the 0.8.x branch - moving to 0.9.0.

**Comment by jcklie** [comment]
@jcklie Please have a look

**Comment by jcklie** [comment]
@MdeBoer95 You can do it, I do not mind.
