### ISSUE TITLE
Creating a statement with KB resource and empty value throws

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1095]
**Describe the bug**
Creating a statement with KB resource and empty value throws

**To Reproduce**
1. Go to the KB page
2. Create a statement with KB resource and empty value 
3. Tab out

```
java.lang.NullPointerException: null
	at de.tudarmstadt.ukp.inception.ui.kb.value.editor.IRIValueEditor$1.lambda$getChoices$0(IRIValueEditor.java:98) ~[classes/:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
```

**Expected behavior**
No error

**Screenshots**

**Please complete the following information:**
 - Version and build ID: 5692bf8f43e2e4762753f55dec56296839578191
 - OS: Linux
 - Browser: Chrome

**Additional context**
I used the Wine ontology.

**Comment by reckart** [comment]
Need to check here as well if this applies to the 0.8.x branch...

**Comment by reckart** [comment]
Problem exists in 0.8.3-SNAPSHOT (2019-04-04 20:24:21, build f7a7cb116c5ce51eab5b1da694df931e0476190e) as well but with a different stack trace:

```
2019-04-05 08:55:27 ERROR [rec] KnowledgeBasePage - Error: null
java.lang.NullPointerException: null
	at org.cyberborean.rdfbeans.datatype.DefaultDatatypeMapper.getRDFValue(DefaultDatatypeMapper.java:114) ~[rdfbeans-2.2.jar!/:?]
	at de.tudarmstadt.ukp.inception.kb.InceptionValueMapper.mapValue(InceptionValueMapper.java:66) ~[inception-kb-0.8.3-SNAPSHOT.jar!/:?]
	at de.tudarmstadt.ukp.inception.kb.InceptionValueMapper.mapStatementValue(InceptionValueMapper.java:40) ~[inception-kb-0.8.3-SNAPSHOT.jar!/:?]
	at de.tudarmstadt.ukp.inception.kb.reification.NoReification.reify(NoReification.java:76) ~[inception-kb-0.8.3-SNAPSHOT.jar!/:?]
	at de.tudarmstadt.ukp.inception.kb.reification.NoReification.lambda$upsertStatement$2(NoReification.java:232) ~[inception-kb-0.8.3-SNAPSHOT.jar!/:?]
	at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl.update(KnowledgeBaseServiceImpl.java:833) ~[inception-kb-0.8.3-SNAPSHOT.jar!/:?]
	at de.tudarmstadt.ukp.inception.kb.reification.NoReification.upsertStatement(NoReification.java:228) ~[inception-kb-0.8.3-SNAPSHOT.jar!/:?]
	at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl.upsertStatement(KnowledgeBaseServiceImpl.java:772) ~[inception-kb-0.8.3-SNAPSHOT.jar!/:?]
...
``

**Comment by jcklie** [comment]
@reckart We solved this, didnt we?

**Comment by UWinch** [comment]
Has been merged
