### ISSUE TITLE
Inception fails to start running in docker 

### ISSUE THREAD

**Issue by davanstrien** [inception-project/inception#1291]
Not sure if this is a bug so haven't flagged as one but support would be hugely appreciated.  Inception runs into an error during startup. Inception has been setup using the Docker compose from the documentation running on Ubunutu 18.04. 

Startup logs from the docker container:

```
0.9.1 (2019-05-22 12:22:50, build 5a92d84bb0db61bb49018dd171fa0d8026b4f541)

2019-07-10 10:12:10 INFO [SYSTEM] InceptionApplicationContextInitializer - Authentication: database
2019-07-10 10:12:10 INFO [SYSTEM] INCEpTION - Starting INCEpTION on 27cceab896a7 with PID 6 (/opt/inception/inception-app-standalone.jar started by root in /opt/inception)
2019-07-10 10:12:10 INFO [SYSTEM] INCEpTION - The following profiles are active: auto-mode-builtin
2019-07-10 10:17:18 WARN [SYSTEM] AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by 27cceab896a7 (172.18.0.2) since 7/9/19 9:46 AM
2019-07-10 10:17:20 ERROR [SYSTEM] SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by 27cceab896a7 (172.18.0.2) since 7/9/19 9:46 AM
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:307) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124) ~[spring-boot-1.5.21.RELEASE.jar!/:1.5.21.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.21.RELEASE.jar!/:1.5.21.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.21.RELEASE.jar!/:1.5.21.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.21.RELEASE.jar!/:1.5.21.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.5.21.RELEASE.jar!/:1.5.21.RELEASE]
	at de.tudarmstadt.ukp.inception.INCEpTION.main(INCEpTION.java:181) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [inception-app-standalone.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [inception-app-standalone.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [inception-app-standalone.jar:?]
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) [inception-app-standalone.jar:?]
Caused by: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by 27cceab896a7 (172.18.0.2) since 7/9/19 9:46 AM
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:190) ~[liquibase-core-3.5.5.jar!/:?]
	at liquibase.Liquibase.update(Liquibase.java:196) ~[liquibase-core-3.5.5.jar!/:?]
	at liquibase.Liquibase.update(Liquibase.java:192) ~[liquibase-core-3.5.5.jar!/:?]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:431) ~[liquibase-core-3.5.5.jar!/:?]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388) ~[liquibase-core-3.5.5.jar!/:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	... 25 more
```

Happy to provide any more required information to help resolve.

**Comment by reckart** [comment]
That sounds like you may have had some trouble in starting up/shutting down INCEpTION and a lock flag remained in the DB. There is a table `DATABASECHANGELOGLOCK` in the DB which contains this flag. Setting it back to `0` or clearing the table should resolve the problem. But when starting INCEpTION again, please check if there might be a new error now, potentially one related to problems setting up the database schema.

**Comment by reckart** [comment]
You'll have to use a separate database client to access that table. It cannot be done through INCEpTION. If you are using a MySQL/MariaDB, this should be pretty straightforard.

**Comment by davanstrien** [comment]
We're running a seperate mysql docker container with the data held outside the container as suggested in the documentation. Can I remove that table directly or will I need to access the mysql running in the docker container? (sorry don't have much experience with sql servers)

**Comment by reckart** [comment]
I'd say access the MySQL running in the container. If you delete data files of MySQL on disk, there could be collateral damage.

**Comment by davanstrien** [comment]
Thanks so much! That has fixed it 😄. Is the lock to the DB only applied while annotations are being entered? Wondering if avoiding shutdown while annotations in progress is the best way to try and avoid this happening again?

**Comment by reckart** [comment]
The lock only exists for a short time during startup while Liquibase updates the database schema (if necessary). Once the application is up and running, the lock is already long removed. So to avoid having it, don't kill the application during startup :)
