### ISSUE TITLE
OpenNlp NER fails to evaluate

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1317]
**Describe the bug**
Evaluation fails with:

2019-07-18 14:35:38 ERROR [SYSTEM] SelectionTask - [admin][[Named entity@value] Multi-Token Sequence Classifier (OpenNLP NER)]: Failed
java.lang.NoSuchMethodError: it.unimi.dsi.fastutil.objects.Object2IntMap.get(Ljava/lang/Object;)Ljava/lang/Integer;
	at de.tudarmstadt.ukp.inception.recommendation.imls.opennlp.ner.OpenNlpNerRecommender.extractAnnotatedSpans(OpenNlpNerRecommender.java:353) ~[inception-imls-opennlp-0.11.0-SNAPSHOT.jar:?]
	at de.tudarmstadt.ukp.inception.recommendation.imls.opennlp.ner.OpenNlpNerRecommender.createNameSample(OpenNlpNerRecommender.java:316) ~[inception-imls-opennlp-0.11.0-SNAPSHOT.jar:?]
	at de.tudarmstadt.ukp.inception.recommendation.imls.opennlp.ner.OpenNlpNerRecommender.extractNameSamples(OpenNlpNerRecommender.java:300) ~[inception-imls-opennlp-0.11.0-SNAPSHOT.jar:?]
	at de.tudarmstadt.ukp.inception.recommendation.imls.opennlp.ner.OpenNlpNerRecommender.evaluate(OpenNlpNerRecommender.java:161) ~[inception-imls-opennlp-0.11.0-SNAPSHOT.jar:?]
	at de.tudarmstadt.ukp.inception.recommendation.tasks.SelectionTask.run(SelectionTask.java:162) [inception-recommendation-0.11.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**To Reproduce**
1. Configure the Opennlp NER Recommender
2. Go to the annotationpage and make some annotations
3. Check the command line output

**Please complete the following information:**
 - Version and build ID: 0.11.0 SNAPSHOT

**Comment by UWinch** [comment]
Weirdly stopped occurring and only happened on one machine.
