### ISSUE TITLE
Delete project endpoint fails with python's requests library

### ISSUE THREAD

**Issue by JavierLuna** [inception-project/inception#1349]
**Describe the bug**
When trying to perform a delete request against the API, via python using the `requests` library, it will return a strange error:
```
{"messages":[{"level":"ERROR","message":"Internal server error: Argument 'requestCycle' may not be null."}]}
```
Tried doing it using `curl` and it works fine, but performing the very same request with python fails.

**To Reproduce**
1. Have user `remote` with password `a`, capable of using the API.
2. Have project with id `1`
3. Have Python 3.6 installed with latest `requests` library installed
4. Executing:
```python
import requests

response = requests.delete(f"http://inception-host.com/api/aero/v1/projects/1", auth=('remote', 'a'))
print(response.status_code) # This will print 500
print(response.text) # This will print the error message I described earlier
```
**Expected behavior**
A good status code and the project deleted. Working as expected.

**Please complete the following information:**
 - Version and build ID:  INCEpTION -- 0.10.2 (2019-07-15 13:25:06, build 473575ebd94f22dcd61bdec3d41c2d816aabd17c) 
 - OS: Ubuntu 18.04
 - Browser: Firefox but not applicable
 - Python version: Python 3.6.9
 - requests version: 2.18.4

**Comment by reckart** [comment]
If this works with curl but not with Python, the problem can likely be solved on your side. Of course the error message should be better. I expect that there is an underlying error and the error you see is a problem trying to render the error message of the other underlying error. Try looking into the server logs to see if you can get some information on the underlying error.

**Comment by JavierLuna** [comment]
I found the logs:
```
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295) ~[spring-tx-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at de.tudarmstadt.ukp.clarin.webanno.project.ProjectServiceImpl$$FastClassBySpringCGLIB$$87162b14.invoke(<generated>) ~[webanno-project-3.6.0-beta-11.jar!/:?]
at de.tudarmstadt.ukp.clarin.webanno.project.ProjectServiceImpl.removeProject(ProjectServiceImpl.java:628) ~[webanno-project-3.6.0-beta-11.jar!/:?]
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:142) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:179) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:261) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at sun.reflect.GeneratedMethodAccessor1789.invoke(Unknown Source) ~[?:?]
at de.tudarmstadt.ukp.inception.ui.core.menubar.MenuBarEventAdapter.onProjectDeleted(MenuBarEventAdapter.java:36) ~[inception-ui-core-0.10.2.jar!/:?]
at org.apache.wicket.Session.get(Session.java:175) ~[wicket-core-8.3.0.jar!/:8.3.0]
at org.apache.wicket.Application.fetchCreateAndSetSession(Application.java:1550) ~[wicket-core-8.3.0.jar!/:8.3.0]
at org.apache.wicket.util.lang.Args.notNull(Args.java:41) ~[wicket-util-8.3.0.jar!/:8.3.0]
java.lang.IllegalArgumentException: Argument 'requestCycle' may not be null.
ERROR [remote] AeroRemoteApiController - Argument 'requestCycle' may not be null. 
```

I also modified the script to see if it was the `requests`'s library fault or not, but I was able to reproduce it via `urllib`  which comes in the standard python libraries:
```
import os
import urllib3
import requests
import base64
http = urllib3.PoolManager()
base64string = base64.b64encode('remote:a'.encode('utf-8'))
r = http.request('DELETE',f"http://inception.savanamed.com/api/aero/v1/projects/{p['id']}", headers={'Authorization': f"Basic {base64string.decode('utf-8')}"})
print(r.status)
print(r.data.decode('utf-8'))

```

**Comment by JavierLuna** [comment]
I found the logs:
```
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295) ~[spring-tx-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at de.tudarmstadt.ukp.clarin.webanno.project.ProjectServiceImpl$$FastClassBySpringCGLIB$$87162b14.invoke(<generated>) ~[webanno-project-3.6.0-beta-11.jar!/:?]
at de.tudarmstadt.ukp.clarin.webanno.project.ProjectServiceImpl.removeProject(ProjectServiceImpl.java:628) ~[webanno-project-3.6.0-beta-11.jar!/:?]
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:142) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:179) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:261) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at sun.reflect.GeneratedMethodAccessor1789.invoke(Unknown Source) ~[?:?]
at de.tudarmstadt.ukp.inception.ui.core.menubar.MenuBarEventAdapter.onProjectDeleted(MenuBarEventAdapter.java:36) ~[inception-ui-core-0.10.2.jar!/:?]
at org.apache.wicket.Session.get(Session.java:175) ~[wicket-core-8.3.0.jar!/:8.3.0]
at org.apache.wicket.Application.fetchCreateAndSetSession(Application.java:1550) ~[wicket-core-8.3.0.jar!/:8.3.0]
at org.apache.wicket.util.lang.Args.notNull(Args.java:41) ~[wicket-util-8.3.0.jar!/:8.3.0]
java.lang.IllegalArgumentException: Argument 'requestCycle' may not be null.
ERROR [remote] AeroRemoteApiController - Argument 'requestCycle' may not be null.
```

I was able to reproduce it without the `requests` library, using `urllib3` which is part of the standard Python library.

Also, I double checked and the requests made in the script comply with the swagger spec. What could it be? Could you point me to the tests made against the api to see if I am missing any headers or whatnot?

```
import os
import urllib3
import requests
import base64
http = urllib3.PoolManager()

base64string = base64.b64encode('remote:a'.encode('utf-8'))
r = http.request('DELETE',f"http://inception-host.com/api/aero/v1/projects/1", headers={'Authorization': f"Basic {base64string.decode('utf-8')}"})
print(r.status)
print(r.data.decode('utf-8'))
```

**Comment by reckart** [comment]
Ok, thanks. Looks like something may have changed in Wicket and the following lines now produce an exception when called outside a Wicket request:

**MenuBarEventAdapter**
```
Session session = Session.get();
        if (session != null) {
```

That should be fixable :)

I still wonder though why curl works for you... if it fails with this message, it should fail consistently.

**Comment by JavierLuna** [comment]
That is great news!

I know, I thought the same. Weird thing is that if I call the exact curl command from Python (using `os.system()`, then the curl command doesn't work.

Thank you so much for your time and for taking a look at this :)
