### ISSUE TITLE
Error accepting recommendations

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1376]
**Describe the bug**
Accepting recommendations results in error:
```
BratAnnotationEditor - Error: CAS does not contain any [de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS] at [28,29]
java.lang.IllegalArgumentException: CAS does not contain any [de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS] at [28,29]
	at org.apache.uima.fit.util.CasUtil.selectSingleAt(CasUtil.java:329) ~[uimafit-core-2.4.0.jar:2.4.0]
	at de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl.upsertFeature(RecommendationServiceImpl.java:625) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl$$FastClassBySpringCGLIB$$7b2c1577.invoke(<generated>) ~[classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl$$EnhancerBySpringCGLIB$$949cd2bd.upsertFeature(<generated>) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.recommendation.RecommendationEditorExtension.actionAcceptRecommendation(RecommendationEditorExtension.java:163) ~[classes/:?]
```
**To Reproduce**
1. Configure project with opnenlp pos recommender for POS tags
2. Open document to get some suggestions.
3. Accept suggestion.

**Please complete the following information:**
 - Version and build ID: [0.12.0-SNAPSHOT
 - OS: ubuntu
 - Browser: chrome

**Comment by reckart** [comment]
Does this also happen in 0.11.1?

**Comment by UWinch** [comment]
I tested a bit more and it seems that no recommendations can be accepted at the moment for 0.11.1 and 0.12.0.
