### ISSUE TITLE
Selecting entities throws NoSuchElementException

### ISSUE THREAD

**Issue by rcffc** [inception-project/inception#162]
When I click on an entity, I get this error:
```
Caused by: java.util.NoSuchElementException
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_152]
	at de.tudarmstadt.ukp.inception.ui.kb.feature.ConceptFeatureSupport.getFeatureValue(ConceptFeatureSupport.java:204) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.ui.kb.feature.ConceptFeatureSupport.getFeatureValue(ConceptFeatureSupport.java:66) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.annotation.adapter.TypeAdapter_ImplBase.getFeatureValue(TypeAdapter_ImplBase.java:132) ~[webanno-api-annotation-3.4.0-20180501.122156-154.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.ui.annotation.detail.AnnotationDetailEditorPanel.loadFeatureEditorModelsCommon(AnnotationDetailEditorPanel.java:1096) ~[webanno-ui-annotation-3.4.0-20180501.122212-154.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.ui.annotation.detail.AnnotationDetailEditorPanel.loadFeatureEditorModels(AnnotationDetailEditorPanel.java:1044) ~[webanno-ui-annotation-3.4.0-20180501.122212-154.jar:?]
	... 152 more
```
It is quite strange because I have tested this with the latest code but also with an old commit 229cf77eb882b18370e65c468dac614473ccca23 which should be running fine on blinky-testing.  

![peek 2018-05-04 14-26](https://user-images.githubusercontent.com/13070150/39627752-2ddc335a-4fa7-11e8-9011-14e6c86c1af0.gif)

**Comment by rcffc** [comment]
Can someone confirm this behavior?

**Comment by rcffc** [comment]
Solved, wrong KB settings.
