### ISSUE TITLE
Cannot export XMI document: ClassCastException

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1627]
**Describe the bug**

When I try to export an XMI document I imported before, then it fails.

Example: https://pastebin.com/rdxruC2B

**To Reproduce**
1. Import the document as XMI
2. Export the project as XMI
3. See error

**Expected behavior**
Export works and it is the same document as I imported.

**Error**

<details><summary>CLICK ME</summary>
<p>

```
2020-03-03 15:26:05 INFO [admin] DocumentServiceImpl - Loading initial CAS for source document [sn82014385-1810-01-06-a-i0001 preinception.xmi](22) in project [JCK: Matteo XMI](7)
2020-03-03 15:26:06 INFO [admin] DocumentServiceImpl - Imported source document [sn82014385-1810-01-06-a-i0001 preinception.xmi](22) to project [JCK: Matteo XMI](7)
2020-03-03 15:26:06 INFO [admin] ApplicationPageBase - admin: Document [sn82014385-1810-01-06-a-i0001 preinception.xmi] has been imported successfully!
2020-03-03 15:26:06 INFO [SYSTEM] SearchServiceImpl - Re-indexing project [JCK: Matteo XMI](7) 
2020-03-03 15:26:06 INFO [SYSTEM] MtasDocumentIndex - Indexing all documents in the project [JCK: Matteo XMI](7)
2020-03-03 15:26:06 INFO [SYSTEM] DocumentServiceImpl - Loading initial CAS for source document [sn82014385-1810-01-06-a-i0001 preinception.xmi](22) in project [JCK: Matteo XMI](7)
2020-03-03 15:26:07 INFO [SYSTEM] MtasDocumentIndex - All documents have been indexed in the project [JCK: Matteo XMI](7)
2020-03-03 15:26:15 INFO [admin] DocumentServiceImpl - Created annotation document [23] for user [admin] for source document [sn82014385-1810-01-06-a-i0001 preinception.xmi](22) in project [JCK: Matteo XMI](7)
2020-03-03 15:26:15 INFO [admin] DocumentServiceImpl - Loading initial CAS for source document [sn82014385-1810-01-06-a-i0001 preinception.xmi](22) in project [JCK: Matteo XMI](7)
2020-03-03 15:26:15 INFO [admin] AnnotationSchemaServiceImpl - Upgraded CAS of user [admin] for document [sn82014385-1810-01-06-a-i0001 preinception.xmi](22) in project [JCK: Matteo XMI](7)
2020-03-03 15:26:31 INFO [admin] KnowledgeBaseExporter - Exported [0] knowledge bases for project [JCK: Matteo XMI]
2020-03-03 15:26:31 INFO [admin] GazeteerExporter - Exported [0] gazeteers for project [JCK: Matteo XMI]
2020-03-03 15:26:31 INFO [admin] ChainExporter - Exported [0] chains for project [JCK: Matteo XMI]
2020-03-03 15:26:31 INFO [admin] LoggedEventExporter - Exported [9] logged events for project [JCK: Matteo XMI]
2020-03-03 15:26:31 INFO [admin] LoggedEventExporter - Skipped [1] logged events for [1] documents no longer existing
2020-03-03 15:26:31 INFO [admin] SourceDocumentExporter - Exported content for source document [22] in project [JCK: Matteo XMI] with id [7]
2020-03-03 15:26:31 INFO [admin] PermissionsExporter - Exported [3] permissions for project [JCK: Matteo XMI]
2020-03-03 15:26:32 INFO [admin] LayerExporter - Exported [12] layers for project [JCK: Matteo XMI]
2020-03-03 15:26:32 INFO [admin] TagSetExporter - Exported [7] tagsets for project [JCK: Matteo XMI]
2020-03-03 15:26:32 INFO [admin] LoggedEventExporter - Exported [0] document repositories for project [JCK: Matteo XMI]
2020-03-03 15:26:32 INFO [admin] RecommenderExporter - Exported [0] recommenders for project [JCK: Matteo XMI]
2020-03-03 15:26:32 INFO [admin] DocumentServiceImpl - Loading initial CAS for source document [sn82014385-1810-01-06-a-i0001 preinception.xmi](22) in project [JCK: Matteo XMI](7)
2020-03-03 15:26:32 INFO [admin] AnnotationDocumentExporter - Exported annotation document content for user [INITIAL_CAS] for source document [22] in project [JCK: Matteo XMI] with id [7]
2020-03-03 15:26:32 ERROR [admin] AggregateAnalysisEngine_impl - Exception occurred
java.lang.ClassCastException: com.sun.proxy.$Proxy205 cannot be cast to org.apache.uima.cas.impl.CASImpl
	at org.apache.uima.analysis_engine.asb.impl.FlowContainer.<init>(FlowContainer.java:55) ~[uimaj-core-3.1.1.jar:3.1.1]
	at org.apache.uima.analysis_engine.asb.impl.FlowControllerContainer.computeFlow(FlowControllerContainer.java:235) ~[uimaj-core-3.1.1.jar:3.1.1]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:406) ~[uimaj-core-3.1.1.jar:3.1.1]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344) ~[uimaj-core-3.1.1.jar:3.1.1]
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:271) ~[uimaj-core-3.1.1.jar:3.1.1]
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:272) ~[uimaj-core-3.1.1.jar:3.1.1]
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:318) ~[uimafit-core-3.0.0.jar:3.0.0]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl.exportCasToFile(ImportExportServiceImpl.java:451) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl.exportAnnotationDocument(ImportExportServiceImpl.java:232) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl$$FastClassBySpringCGLIB$$256f1e29.invoke(<generated>) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366) ~[spring-tx-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99) ~[spring-tx-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl$$EnhancerBySpringCGLIB$$45740366.exportAnnotationDocument(<generated>) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.exporters.AnnotationDocumentExporter.exportAnnotationDocumentContents(AnnotationDocumentExporter.java:210) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.exporters.AnnotationDocumentExporter.exportData(AnnotationDocumentExporter.java:103) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl.exportProject(ProjectExportServiceImpl.java:222) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl.exportProject(ProjectExportServiceImpl.java:167) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl$$FastClassBySpringCGLIB$$3d43e16f.invoke(<generated>) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366) [spring-tx-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99) [spring-tx-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) [spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) [spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl$$EnhancerBySpringCGLIB$$e70b88f8.exportProject(<generated>) [webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportFullProjectTask.export(ProjectExportFullProjectTask.java:46) [webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportTask_ImplBase.run(ProjectExportTask_ImplBase.java:79) [webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2020-03-03 15:26:32 ERROR [admin] ProjectExportFullProjectTask - Unexpected error during project export
de.tudarmstadt.ukp.clarin.webanno.api.export.ProjectExportException: Project export failed
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl.exportProject(ProjectExportServiceImpl.java:241) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl.exportProject(ProjectExportServiceImpl.java:167) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl$$FastClassBySpringCGLIB$$3d43e16f.invoke(<generated>) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366) ~[spring-tx-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99) ~[spring-tx-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl$$EnhancerBySpringCGLIB$$e70b88f8.exportProject(<generated>) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportFullProjectTask.export(ProjectExportFullProjectTask.java:46) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportTask_ImplBase.run(ProjectExportTask_ImplBase.java:79) [webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:283) ~[uimaj-core-3.1.1.jar:3.1.1]
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:272) ~[uimaj-core-3.1.1.jar:3.1.1]
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:318) ~[uimafit-core-3.0.0.jar:3.0.0]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl.exportCasToFile(ImportExportServiceImpl.java:451) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl.exportAnnotationDocument(ImportExportServiceImpl.java:232) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl$$FastClassBySpringCGLIB$$256f1e29.invoke(<generated>) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366) ~[spring-tx-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99) ~[spring-tx-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl$$EnhancerBySpringCGLIB$$45740366.exportAnnotationDocument(<generated>) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.exporters.AnnotationDocumentExporter.exportAnnotationDocumentContents(AnnotationDocumentExporter.java:210) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.exporters.AnnotationDocumentExporter.exportData(AnnotationDocumentExporter.java:103) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl.exportProject(ProjectExportServiceImpl.java:222) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	... 19 more
Caused by: java.lang.ClassCastException: com.sun.proxy.$Proxy205 cannot be cast to org.apache.uima.cas.impl.CASImpl
	at org.apache.uima.analysis_engine.asb.impl.FlowContainer.<init>(FlowContainer.java:55) ~[uimaj-core-3.1.1.jar:3.1.1]
	at org.apache.uima.analysis_engine.asb.impl.FlowControllerContainer.computeFlow(FlowControllerContainer.java:235) ~[uimaj-core-3.1.1.jar:3.1.1]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:406) ~[uimaj-core-3.1.1.jar:3.1.1]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344) ~[uimaj-core-3.1.1.jar:3.1.1]
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:271) ~[uimaj-core-3.1.1.jar:3.1.1]
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:272) ~[uimaj-core-3.1.1.jar:3.1.1]
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:318) ~[uimafit-core-3.0.0.jar:3.0.0]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl.exportCasToFile(ImportExportServiceImpl.java:451) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl.exportAnnotationDocument(ImportExportServiceImpl.java:232) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl$$FastClassBySpringCGLIB$$256f1e29.invoke(<generated>) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366) ~[spring-tx-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99) ~[spring-tx-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl$$EnhancerBySpringCGLIB$$45740366.exportAnnotationDocument(<generated>) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.exporters.AnnotationDocumentExporter.exportAnnotationDocumentContents(AnnotationDocumentExporter.java:210) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.exporters.AnnotationDocumentExporter.exportData(AnnotationDocumentExporter.java:103) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl.exportProject(ProjectExportServiceImpl.java:222) ~[webanno-api-dao-4.0.0-20200302.224354-147.jar:?]
	... 19 more
2020-03-03 15:26:33 ERROR [admin] ApplicationPageBase - admin: Unexpected error during project export: ClassCastException: com.sun.proxy.$Proxy205 cannot be cast to org.apache.uima.cas.impl.CASImpl
2020-03-03 15:26:33 ERROR [admin] ApplicationPageBase - admin: Project export failed
```
</p>
</details>

**Please complete the following information:**
 - Version and build ID:  0.15.0-SNAPSHOT 628e5454d7c5557e42c01ea0c6dad3e933f9e040
 - OS: Linux
 - Browser: Chrome

**Comment by reckart** [comment]
This only happens with `-Dwebanno.debug.enforce_cas_thread_lock=true`.

Fixed upstream: https://github.com/webanno/webanno/commit/22b2800c6ea1944e47128d82b2de6e505898871d
