### ISSUE TITLE
SASS does not compile on Windows

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1636]
**Describe the bug**
SASS does not compile on Windows when going to the INCEpTION web page.

**To Reproduce**
1. Start INCEpTION in intellij on WIndows
2. Go to localhost:8080
3. See error

<details><summary>Error message</summary>
<p>

```
2020-03-15 17:06:51 WARN [anonymousUser] NativeImporterWrapper - Illegal char <:> at index 3: jar:file:/C:/Users/klie/.m2/repository/org/webjars/bootstrap/4.4.1-1/bootstrap-4.4.1-1.jar!/META-INF/resources/webjars/bootstrap/4.4.1-1/scss/bootstrap.scss
java.nio.file.InvalidPathException: Illegal char <:> at index 3: jar:file:/C:/Users/klie/.m2/repository/org/webjars/bootstrap/4.4.1-1/bootstrap-4.4.1-1.jar!/META-INF/resources/webjars/bootstrap/4.4.1-1/scss/bootstrap.scss
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229) ~[?:?]
	at java.nio.file.Path.of(Path.java:147) ~[?:?]
	at java.nio.file.Paths.get(Paths.java:69) ~[?:?]
	at de.tudarmstadt.ukp.clarin.webanno.support.sass.UrlImporter.getAbsolutePath(UrlImporter.java:256) ~[webanno-support-4.0.0-20200310.215039-154.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.support.sass.UrlImporter.resolveLocalDependency(UrlImporter.java:208) ~[webanno-support-4.0.0-20200310.215039-154.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.support.sass.UrlImporter.tryResolveUrl(UrlImporter.java:107) ~[webanno-support-4.0.0-20200310.215039-154.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.support.sass.UrlImporter.lambda$apply$0(UrlImporter.java:86) ~[webanno-support-4.0.0-20200310.215039-154.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:?]
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:720) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543) ~[?:?]
	at de.tudarmstadt.ukp.clarin.webanno.support.sass.UrlImporter.apply(UrlImporter.java:87) ~[webanno-support-4.0.0-20200310.215039-154.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.support.sass.TrackingImporter.apply(TrackingImporter.java:60) ~[webanno-support-4.0.0-20200310.215039-154.jar:?]
	at io.bit3.jsass.adapter.NativeImporterWrapper.apply(NativeImporterWrapper.java:39) [jsass-5.10.3.jar:5.10.3]
	at io.bit3.jsass.adapter.NativeAdapter.compileString(Native Method) ~[jsass-5.10.3.jar:5.10.3]
	at io.bit3.jsass.adapter.NativeAdapter.compile(NativeAdapter.java:55) [jsass-5.10.3.jar:5.10.3]
	at io.bit3.jsass.Compiler.compile(Compiler.java:114) [jsass-5.10.3.jar:5.10.3]
	at io.bit3.jsass.Compiler.compileString(Compiler.java:64) [jsass-5.10.3.jar:5.10.3]
	at io.bit3.jsass.Compiler.compileString(Compiler.java:47) [jsass-5.10.3.jar:5.10.3]
	at de.tudarmstadt.ukp.clarin.webanno.support.sass.SassCacheManager.getCss(SassCacheManager.java:167) [webanno-support-4.0.0-20200310.215039-154.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.support.sass.SassResourceStream.getString(SassResourceStream.java:65) [webanno-support-4.0.0-20200310.215039-154.jar:?]
	at org.apache.wicket.util.resource.AbstractStringResourceStream.getInputStream(AbstractStringResourceStream.java:172) [wicket-util-8.6.1.jar:8.6.1]
	at org.apache.wicket.request.resource.caching.version.MessageDigestResourceVersion.getVersion(MessageDigestResourceVersion.java:135) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.request.resource.caching.version.CachingResourceVersion.getVersion(CachingResourceVersion.java:116) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.request.resource.caching.FilenameWithVersionResourceCachingStrategy.decorateUrl(FilenameWithVersionResourceCachingStrategy.java:105) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.core.request.mapper.BasicResourceReferenceMapper.mapHandler(BasicResourceReferenceMapper.java:234) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.request.mapper.ParentPathReferenceRewriter.mapHandler(ParentPathReferenceRewriter.java:92) [wicket-request-8.6.1.jar:8.6.1]
	at org.apache.wicket.request.mapper.CompoundRequestMapper.mapHandler(CompoundRequestMapper.java:210) [wicket-request-8.6.1.jar:8.6.1]
	at org.apache.wicket.request.cycle.RequestCycle.mapUrlFor(RequestCycle.java:451) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.request.cycle.RequestCycle.urlFor(RequestCycle.java:551) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.markup.head.CssReferenceHeaderItem.getUrl(CssReferenceHeaderItem.java:162) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.markup.head.CssReferenceHeaderItem.getRenderTokens(CssReferenceHeaderItem.java:149) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.markup.head.internal.HeaderResponse.wasItemRendered(HeaderResponse.java:61) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.markup.head.internal.HeaderResponse.render(HeaderResponse.java:52) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.markup.head.ResourceAggregator.renderHeaderItems(ResourceAggregator.java:311) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.markup.head.ResourceAggregator.close(ResourceAggregator.java:280) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.markup.html.internal.HtmlHeaderContainer.onComponentTagBody(HtmlHeaderContainer.java:176) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2491) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1593) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.Component.internalRender(Component.java:2296) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.Component.render(Component.java:2227) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1454) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1654) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.Page.onRender(Page.java:858) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.markup.html.WebPage.onRender(WebPage.java:126) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.Component.internalRender(Component.java:2296) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.Component.render(Component.java:2227) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.Page.renderPage(Page.java:998) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:202) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:914) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:65) [wicket-request-8.6.1.jar:8.6.1]
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:282) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:253) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:221) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.protocol.ws.AbstractUpgradeFilter.processRequestCycle(AbstractUpgradeFilter.java:70) [wicket-native-websocket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:206) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:299) [wicket-core-8.6.1.jar:8.6.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:186) [spring-orm-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at de.tudarmstadt.ukp.clarin.webanno.support.logging.LoggingFilter.doFilter(LoggingFilter.java:52) [webanno-support-4.0.0-20200310.215039-154.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:150) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) [spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) [spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

</p>
</details>

**Please complete the following information:**
 - Version and build ID: 97168c226b2007e22815c4162c90c72054d7d759 INCEpTION Master
 - OS: Windows
 - Browser: chrome

**Comment by reckart** [comment]
Fixed upstream: https://github.com/webanno/webanno/issues/1632
