### ISSUE TITLE
NPE on session destruction

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#1654]
**Describe the bug**

**To Reproduce**
I don't know how to reproduce it - it happend when I simply started up INCEpTION. But I added a stack trace below

**Expected behavior**
No error.

**Screenshots**
<details>
<summary>Stack trace</summary>

```
java.lang.NullPointerException: null
	at de.tudarmstadt.ukp.clarin.webanno.security.UserDaoImpl.getRoles(UserDaoImpl.java:212) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.security.UserDaoImpl.isAdministrator(UserDaoImpl.java:178) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.security.UserDaoImpl$$FastClassBySpringCGLIB$$ef901b5c.invoke(<generated>) ~[classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) ~[spring-aop-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366) ~[spring-tx-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99) ~[spring-tx-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at de.tudarmstadt.ukp.clarin.webanno.security.UserDaoImpl$$EnhancerBySpringCGLIB$$99144a42.isAdministrator(<generated>) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.project.ProjectServiceImpl.listAccessibleProjects(ProjectServiceImpl.java:726) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.project.ProjectServiceImpl$$FastClassBySpringCGLIB$$87162b14.invoke(<generated>) ~[classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685) ~[spring-aop-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at de.tudarmstadt.ukp.clarin.webanno.project.ProjectServiceImpl$$EnhancerBySpringCGLIB$$cadd7c74.listAccessibleProjects(<generated>) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.curation.CurationServiceImpl.clearState(CurationServiceImpl.java:369) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.curation.CurationServiceImpl.onSessionDestroyed(CurationServiceImpl.java:318) ~[classes/:?]
```

</details>

**Please complete the following information:**
 - Version and build ID: 0.16.0-SNAPSHOT (0e66116607b829be8384ef570b12e3a2cbf5ade4) - likely affect 0.15.0 as well
- Running with Tomcat 9.0.26 in Eclipse

**Comment by reckart** [comment]
The problem occurs when a session is destroyed that belongs to a user who is (no longer) existing in the system. In particular, it always happens when trying to enter the application as in order to access the login page, a session for the user `anonymousUser` is created and then immediately destroyed as the user logs in.
