### ISSUE TITLE
Unit tests on master are failing on Jenkins

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#1766]
**Describe the bug**
Several unit tests are presently failing on master:

* de.tudarmstadt.ukp.inception.recommendation.imls.dl4j.pos.DL4JSequenceRecommenderTest.thatPosPredictionWorks
* de.tudarmstadt.ukp.inception.recommendation.imls.dl4j.pos.DL4JSequenceRecommenderTest.thatNerPredictionWorks
* de.tudarmstadt.ukp.inception.recommendation.imls.lapps.LappsGridRecommenderConformityTest.testNerConformity(LappsGridService{name='ABNER 1.0.0', description='ABNER', url='http://vassar.lappsgrid.org/invoker/anc:gate.abner_1.0.0'}) [0]
* de.tudarmstadt.ukp.inception.recommendation.imls.lapps.LappsGridRecommenderConformityTest.testNerConformity(LappsGridService{name='edu.cmu.lti.oaqa.lapps.LingpipeNER - 1.1.1-SNAPSHOT', description='Lingpipe Named Entity Recognizer with model "English News: MUC-6"', url='http://vassar.lappsgrid.org/invoker/anc:lingpipe.ner_1.1.1-SNAPSHOT'}) [1]

In contrast to the PR builds, master is running with `-Pfull-tests`. If you want to reproduce this locally in a command line build, enable that profile. IDEs should run the tests without any extra work if you run the test classes individually.

**Comment by jcklie** [comment]
The [error messages ](https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/view/INCEpTION/job/INCEpTION%20(GitHub)%20(master)/de.tudarmstadt.ukp.inception.app$inception-imls-lapps/1115/testReport/junit/de.tudarmstadt.ukp.inception.recommendation.imls.lapps/LappsGridRecommenderConformityTest/testNerConformity_LappsGridService_name__ABNER_1_0_0___description__ABNER___url__http___vassar_lappsgrid_org_invoker_anc_gate_abner_1_0_0_____0_/)look really strange:


```
de.tudarmstadt.ukp.inception.recommendation.api.recommender.RecommendationException: Cannot predict
	at de.tudarmstadt.ukp.inception.recommendation.imls.lapps.LappsGridRecommenderConformityTest.predict(LappsGridRecommenderConformityTest.java:133)
	at de.tudarmstadt.ukp.inception.recommendation.imls.lapps.LappsGridRecommenderConformityTest.testNerConformity(LappsGridRecommenderConformityTest.java:94)
Caused by: java.lang.RuntimeException: <html><head><title>Apache Tomcat/6.0.35 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 408 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The client did not produce a request within the time that the server was prepared to wait ().</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/6.0.35</h3></body></html>
	at de.tudarmstadt.ukp.inception.recommendation.imls.lapps.LappsGridRecommenderConformityTest.predict(LappsGridRecommenderConformityTest.java:133)
	at de.tudarmstadt.ukp.inception.recommendation.imls.lapps.LappsGridRecommenderConformityTest.testNerConformity(LappsGridRecommenderConformityTest.java:94)
```

**Comment by reckart** [comment]
@ksuderman Do you have any idea where this error trying to contact the LAPPSGrid services might come from?

**Comment by ksuderman** [comment]
This is our server dying again... Could you send me a list of all the services you call from Inception and I will deploy them to a more stable platform.

**Comment by ksuderman** [comment]
The services are back online and I have fixed the cron script that is supposed to restart Tomcat.

**Comment by UWinch** [comment]
Thanks a lot, the LAPPSGrid tests are working again. 

The other tests fail because of an upstream change in webanno, I'm currently working on it.
