### ISSUE TITLE
WriteAccessNotPermittedException when deleting feature, followed by more errors

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#1789]
**Describe the bug**
In a certain scenario, creating and deleting a feature causes a series of errors.

**To Reproduce**
1. Create new document, upload plaintext document
2. Add one Chunk span annotation
3. In project settings, create new span layer
4. Add new feature (name and type do not matter)
5. Try to delete the feature again, click confirm
6. The dialog fails with `Error: de.tudarmstadt.ukp.clarin.webanno.api.casstorage.WriteAccessNotPermittedException: CAS [lorem%20ipsum.txt](bugert) not found in current sesssion`
7. Click confirm again
8. The dialog fails with ` Error: attempt to create merge event with null entity `
9. Now you can cancel the dialog, then try deleting the feature again and you will be greeted with a `Unexpected RuntimeException` 
10. Refresh the page: the feature is gone in the `Features` list

**Expected behavior**
Step 6 succeeds

**Please complete the following information:**
 - Version and build ID: 0.17.0-SNAPSHOT (2020-06-05 13:19:57, build 6b5895f9be926d48f0c2f51ac79e9ae3ae475020) 
 - OS: Ubunt 20.04
 - Browser: FF 79.0

**Comment by UWinch** [comment]
Seems to happen as soon as an annotation doc exists, the stack trace is:

```

Caused by: de.tudarmstadt.ukp.clarin.webanno.api.casstorage.WriteAccessNotPermittedException: CAS [barack_obama.txt](admin) not found in current sesssion
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.CasStorageSession.assertWritingPermitted(CasStorageSession.java:400) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.AnnotationSchemaServiceImpl.upgradeCas(AnnotationSchemaServiceImpl.java:1017) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.AnnotationSchemaServiceImpl.upgradeCas(AnnotationSchemaServiceImpl.java:1005) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.AnnotationSchemaServiceImpl.upgradeCas(AnnotationSchemaServiceImpl.java:938) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.AnnotationSchemaServiceImpl.upgradeCas(AnnotationSchemaServiceImpl.java:920) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.AnnotationSchemaServiceImpl$$FastClassBySpringCGLIB$$c4446552.invoke(<generated>) ~[classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.AnnotationSchemaServiceImpl$$EnhancerBySpringCGLIB$$9f4532cd.upgradeCas(<generated>) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.CasStorageServiceImpl.upgradeCas(CasStorageServiceImpl.java:877) ~[classes/:?]
	... 115 more

```

**Comment by reckart** [comment]
Fixed upstream.
