### ISSUE TITLE
Documents will not open if constraint rules include non-ASCII characters

### ISSUE THREAD

**Issue by llaska** [inception-project/inception#1827]
**Describe the bug**
Documents will not open after the installation of 0.17.0. The problem seems to happen only in projects that have a local knowledge base.
Error message:
Lexical error at line 4, column 8. Encountered: "\u0440" (1088), after : "\""

**To Reproduce**
1. Go to 'Annotation'
2. Click on 'Open document'
3. Get a blank page with an error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/61777631/95829851-80cdbe00-0d3f-11eb-8527-4c96df743f0a.png)

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 0.17.0 (2020-10-07 11:44:43, build a4ce83232f58eba5968ccdf27c49c099c5e6a4ac)
 - OS: Windows
 - Browser: Firefox

**Comment by UWinch** [comment]
Thanks for bringing this to our attention. Could you check if there is some additional information on this error in the log?

**Comment by llaska** [comment]
Our developer says he cannot find the error or he does not know where to look...
Here's the log.
[inception-1.log](https://github.com/inception-project/inception/files/5370409/inception-1.log)

**Comment by reckart** [comment]
Looks like there is a problem with encoding in the parser for the constraint rules:

```
2020-10-13 06:56:50 ERROR [Laska] AnnotationPage - Error: Lexical error at line 4, column 8.  Encountered: "\u0440" (1088), after : "\""
de.tudarmstadt.ukp.clarin.webanno.constraints.grammar.TokenMgrException: Lexical error at line 4, column 8.  Encountered: "\u0440" (1088), after : "\""
	at de.tudarmstadt.ukp.clarin.webanno.constraints.grammar.ConstraintsParserTokenManager.getNextToken(ConstraintsParserTokenManager.java:510) ~[webanno-constraints-4.0.0-beta-16.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.constraints.grammar.ConstraintsParser.jj_consume_token(ConstraintsParser.java:1079) ~[webanno-constraints-4.0.0-beta-16.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.constraints.grammar.ConstraintsParser.condition(ConstraintsParser.java:327) ~[webanno-constraints-4.0.0-beta-16.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.constraints.grammar.ConstraintsParser.conditions(ConstraintsParser.java:278) ~[webanno-constraints-4.0.0-beta-16.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.constraints.grammar.ConstraintsParser.rule(ConstraintsParser.java:239) ~[webanno-constraints-4.0.0-beta-16.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.constraints.grammar.ConstraintsParser.constraintsSet(ConstraintsParser.java:150) ~[webanno-constraints-4.0.0-beta-16.jar!/:?]
```

I can see a second error which might be a follow-up error triggered by the failure to parse the contraint rules:

```
java.lang.NullPointerException: null
	at de.tudarmstadt.ukp.clarin.webanno.brat.render.BratRenderer.renderUnitsAsRows(BratRenderer.java:311) ~[webanno-brat-4.0.0-beta-16.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.brat.render.BratRenderer.render(BratRenderer.java:139) ~[webanno-brat-4.0.0-beta-16.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.brat.render.BratRenderer.render(BratRenderer.java:116) ~[webanno-brat-4.0.0-beta-16.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.BratAnnotationEditor.render(BratAnnotationEditor.java:755) ~[webanno-brat-4.0.0-beta-16.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.BratAnnotationEditor.bratRenderCommand(BratAnnotationEditor.java:676) ~[webanno-brat-4.0.0-beta-16.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.BratAnnotationEditor.render(BratAnnotationEditor.java:862) ~[webanno-brat-4.0.0-beta-16.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.annotation.AnnotationEditorBase.lambda$requestRender$c8c06b0d$1(AnnotationEditorBase.java:131) ~[webanno-api-annotation-4.0.0-beta-16.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.support.wicket.AjaxComponentRespondListener.onTargetRespond(AjaxComponentRespondListener.java:64) [webanno-support-4.0.0-beta-16.jar!/:?]
```

Can you check your constraint rules via the "constraints" tab in the project settings - maybe a non-ASCII character in/around line 4, column 8.  Encountered: "\u0440" (1088), after : "\"" (https://www.fileformat.info/info/unicode/char/0440/index.htm ?).

Looks like we need to check the configuration of the parser generator which generates the parser for the constraint rules language from the grammar definition and verify that it can deal with Unicode characters... and then do a bugfix release.

**Comment by llaska** [comment]
Yep, there is a cyrillic letter.

**Comment by reckart** [comment]
As a workaround until we have a new version, you could save your constrain rules to a file and then delete them from the system. That should at least allow the users to access the annotation screen again.

**Comment by llaska** [comment]
Yes, that's what we decided to do in order to resume work.
Thank you for your prompt help!

**Comment by reckart** [comment]
Fixed upstream.
