### ISSUE TITLE
MTAS Indexing throws lots of exceptions

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1845]
Annotate things and see the error in the log, e.g. on blinky stable or testing.

```
Nov 06 11:09:55 blinky inception-testing.jar[21135]: 2020-11-06 11:09:55 ERROR [SYSTEM] SearchServiceImpl - Error indexing annotation document [tweet_1235969720777572352.xmi](589) in project [Curriculum Annotation Prestudy](40)
Nov 06 11:09:55 blinky inception-testing.jar[21135]: java.io.IOException: mtas.analysis.util.MtasConfigException: java.lang.reflect.InvocationTargetException : 'null'
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at mtas.analysis.MtasTokenizer.reset(MtasTokenizer.java:175) ~[mtas-7.3.0.3.jar!/:?]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:732) ~[lucene-core-7.3.1.jar!/:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:430) ~[lucene-core-7.3.1.jar!/:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:392) ~[lucene-core-7.3.1.jar!/:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:240) ~[lucene-core-7.3.1.jar!/:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:497) ~[lucene-core-7.3.1.jar!/:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1729) ~[lucene-core-7.3.1.jar!/:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1464) ~[lucene-core-7.3.1.jar!/:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at de.tudarmstadt.ukp.inception.search.index.mtas.MtasDocumentIndex.indexDocument(MtasDocumentIndex.java:889) ~[inception-search-mtas-0.17.2-SNAPSHOT.jar!/:?]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at de.tudarmstadt.ukp.inception.search.index.mtas.MtasDocumentIndex.indexDocument(MtasDocumentIndex.java:1124) ~[inception-search-mtas-0.17.2-SNAPSHOT.jar!/:?]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at de.tudarmstadt.ukp.inception.search.SearchServiceImpl.indexDocument(SearchServiceImpl.java:362) ~[inception-search-core-0.17.2-SNAPSHOT.jar!/:?]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at de.tudarmstadt.ukp.inception.search.SearchServiceImpl$$FastClassBySpringCGLIB$$d6146f50.invoke(<generated>) ~[inception-search-core-0.17.2-SNAPSHOT.jar!/:?]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366) [spring-tx-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) [spring-tx-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) [spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) [spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at de.tudarmstadt.ukp.inception.search.SearchServiceImpl$$EnhancerBySpringCGLIB$$bfaa8613.indexDocument(<generated>) [inception-search-core-0.17.2-SNAPSHOT.jar!/:?]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at de.tudarmstadt.ukp.inception.search.scheduling.tasks.IndexAnnotationDocumentTask.run(IndexAnnotationDocumentTask.java:43) [inception-search-core-0.17.2-SNAPSHOT.jar!/:?]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at de.tudarmstadt.ukp.inception.search.scheduling.TaskConsumer.run(TaskConsumer.java:66) [inception-search-core-0.17.2-SNAPSHOT.jar!/:?]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at java.lang.Thread.run(Thread.java:834) [?:?]
Nov 06 11:09:55 blinky inception-testing.jar[21135]: Caused by: mtas.analysis.util.MtasConfigException: java.lang.reflect.InvocationTargetException : 'null'
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at mtas.analysis.MtasTokenizer.constructTokenCollection(MtasTokenizer.java:251) ~[mtas-7.3.0.3.jar!/:?]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         at mtas.analysis.MtasTokenizer.reset(MtasTokenizer.java:171) ~[mtas-7.3.0.3.jar!/:?]
Nov 06 11:09:55 blinky inception-testing.jar[21135]:         ... 24 more
```

**Comment by reckart** [comment]
I have the impression this might be a follow up exception. In similar projects, I can see that the system tries to acquire a lock but cannot be because it already has one:

```
Dec 21 23:28:27 blinky inception-stable.jar[32537]: org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /srv/inception-stable/repository/project/355/indexMtas/write.lock
Dec 21 23:28:27 blinky inception-stable.jar[32537]:         at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:139) ~[lucene-core-7.3.1.jar!/:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
Dec 21 23:28:27 blinky inception-stable.jar[32537]:         at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41) ~[lucene-core-7.3.1.jar!/:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
Dec 21 23:28:27 blinky inception-stable.jar[32537]:         at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45) ~[lucene-core-7.3.1.jar!/:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
Dec 21 23:28:27 blinky inception-stable.jar[32537]:         at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:948) ~[lucene-core-7.3.1.jar!/:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
Dec 21 23:28:27 blinky inception-stable.jar[32537]:         at de.tudarmstadt.ukp.inception.search.index.mtas.MtasDocumentIndex.getIndexWriter(MtasDocumentIndex.java:241) ~[inception-search-mtas-0.17.2.jar!/:?]
Dec 21 23:28:27 blinky inception-stable.jar[32537]:         at de.tudarmstadt.ukp.inception.search.index.mtas.MtasDocumentIndex.getSearcherManager(MtasDocumentIndex.java:318) ~[inception-search-mtas-0.17.2.jar!/:?]
Dec 21 23:28:27 blinky inception-stable.jar[32537]:         at de.tudarmstadt.ukp.inception.search.index.mtas.MtasDocumentIndex.getTimestamp(MtasDocumentIndex.java:1054) ~[inception-search-mtas-0.17.2.jar!/:?]
Dec 21 23:28:27 blinky inception-stable.jar[32537]:         at de.tudarmstadt.ukp.inception.search.index.mtas.MtasDocumentIndex.indexDocument(MtasDocumentIndex.java:1130) ~[inception-search-mtas-0.17.2.jar!/:?]
Dec 21 23:28:27 blinky inception-stable.jar[32537]:         at de.tudarmstadt.ukp.inception.search.SearchServiceImpl.indexDocument(SearchServiceImpl.java:362) ~[inception-search-core-0.17.2.jar!/:?]
Dec 21 23:28:27 blinky inception-stable.jar[32537]:         at de.tudarmstadt.ukp.inception.search.SearchServiceImpl$$FastClassBySpringCGLIB$$d6146f50.invoke(<generated>) ~[inception-search-core-0.17.2.jar!/:?]
```

This should not happen. Not sure why it happens....
