### ISSUE TITLE
Executable jar does not boot

### ISSUE THREAD

**Issue by Gert-JanVdV** [inception-project/inception#1857]
**Describe the bug**

The jar file through which Inception is normally launched seems to be getting into a boot loop or something. The bug seems to be limited to my desktop, my work laptop doesn't have a problem. I'm not familiar with coding or jar files but this is what I have observed.
The boot begins normally, the "application is loading" banner appears. Initially, Java Platform SE binary uses both the CPU and memory, but for some reason CPU usage begins dropping off very soon after, while Memory use remains stable. Then nothing happens. This very same thing happened on another computer I had access to, but back then I had a back-up so I could just migrate to another computer.
I have tried several things to fix the problem, updated Windows, installed Java updates, then downgraded Java, installed OpenJDK in two different versions. Tried other programs that said they could run this kind of jar file. None of my attempted fixes had any effects.

**Please complete the following information:**
 - Version and build ID: 16.0
 - OS: Windows
 - Browser: Chrome

After trying to boot through the command prompt and leaving it for half an hour this appeared:

```
2020-11-19 15:49:44 INFO [SYSTEM] InceptionApplicationContextInitializer - Authentication: database
2020-11-19 15:49:44 INFO [SYSTEM] INCEpTION - Starting INCEpTION on Sepideh with PID 21860 (C:\Users\gjvdv\OneDrive\Desktop\INCEpTION.jar started by gjvdv in C:\WINDOWS\system32)
2020-11-19 15:49:44 INFO [SYSTEM] INCEpTION - The following profiles are active: auto-mode-builtin
2020-11-19 15:54:50 WARN [SYSTEM] AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by Sepideh (172.31.144.1) since 18/11/20 19:46
2020-11-19 15:54:52 ERROR [SYSTEM] SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by Sepideh (172.31.144.1) since 18/11/20 19:46
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) [spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at de.tudarmstadt.ukp.inception.INCEpTION.main(INCEpTION.java:217) [classes!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [INCEpTION.jar:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [INCEpTION.jar:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [INCEpTION.jar:?]
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58) [INCEpTION.jar:?]
Caused by: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by Sepideh (172.31.144.1) since 18/11/20 19:46
        at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:236) ~[liquibase-core-3.8.8.jar!/:?]
        at liquibase.Liquibase.update(Liquibase.java:184) ~[liquibase-core-3.8.8.jar!/:?]
        at liquibase.Liquibase.update(Liquibase.java:179) ~[liquibase-core-3.8.8.jar!/:?]
        at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:366) ~[liquibase-core-3.8.8.jar!/:?]
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:314) ~[liquibase-core-3.8.8.jar!/:?]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        ... 25 more
```

**Comment by jcklie** [comment]
Can you have a look whether the steps in https://github.com/inception-project/inception/issues/1703 help?

**Comment by Gert-JanVdV** [comment]
> Can you have a look whether the steps in #1703 help?

Yes, initially I feared it didn't work, but after a reboot it works fine. Thank you very much.
