### ISSUE TITLE
https://colab.research.google.com/github/inception-project/inception/blob/master/notebooks/using_pretokenized_and_preannotated_text.ipynb

### ISSUE THREAD

**Issue by jwijffels** [inception-project/inception#2175]
I'm running the examples on Google Colab, namely https://colab.research.google.com/github/inception-project/inception/blob/master/notebooks/using_pretokenized_and_preannotated_text.ipynb

At the call to 
`NamedEntity(begin=27, end=31, value = 'DATE')
`I'm getting: 

```
>>> NamedEntity(begin=27, end=31, value = 'DATE')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\cassis\typesystem.py", line 252, in __call__
    return self._constructor(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'value'
```

**Comment by jwijffels** [comment]
Never mind, forgot to create a Features > value element

**Comment by reckart** [comment]
Glad you found a solution :)
