### ISSUE TITLE
External recommender timeout too short and not configurable

### ISSUE THREAD

**Issue by whisere** [inception-project/inception#2263]
**Describe the bug**
Using remote recommender, try doc with 500 lines (one sentence per line), try auto annotation with the recommender on the annotation page, receive the errors, but the same doc with 300 lines has no problems.

**To Reproduce**
1. Go to annotation page
2. Click on next page
3. inception terminal reports (no errors in inception-external-recommender terminal):
de.tudarmstadt.ukp.inception.recommendation.api.recommender.RecommendationException: Error while sending request!
	at de.tudarmstadt.ukp.inception.recommendation.imls.external.ExternalRecommender.sendRequest(ExternalRecommender.java:276) ~[inception-imls-external-0.19.2.jar!/:?]
	at de.tudarmstadt.ukp.inception.recommendation.imls.external.ExternalRecommender.predict(ExternalRecommender.java:171) ~[inception-imls-external-0.19.2.jar!/:?]
	at de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl.generateSuggestions(RecommendationServiceImpl.java:1312) ~[inception-recommendation-0.19.2.jar!/:?]
	at de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl.computePredictions(RecommendationServiceImpl.java:1199) [inception-recommendation-0.19.2.jar!/:?]
	at de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl$$FastClassBySpringCGLIB$$7b2c1577.invoke(<generated>) [inception-recommendation-0.19.2.jar!/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.3.3.jar!/:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) [spring-aop-5.3.3.jar!/:5.3.3]
	at de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl$$EnhancerBySpringCGLIB$$aed881c1.computePredictions(<generated>) [inception-recommendation-0.19.2.jar!/:?]
	at de.tudarmstadt.ukp.inception.recommendation.tasks.PredictionTask.run(PredictionTask.java:92) [inception-recommendation-0.19.2.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:232) ~[okio-1.17.4.jar!/:?]
	at okio.AsyncTimeout.exit(AsyncTimeout.java:286) ~[okio-1.17.4.jar!/:?]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241) ~[okio-1.17.4.jar!/:?]
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358) ~[okio-1.17.4.jar!/:?]
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230) ~[okio-1.17.4.jar!/:?]
	at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.RealCall.execute(RealCall.java:81) ~[okhttp-3.14.2.jar!/:?]
	at de.tudarmstadt.ukp.inception.recommendation.imls.external.ExternalRecommender.sendRequest(ExternalRecommender.java:273) ~[inception-imls-external-0.19.2.jar!/:?]
	... 11 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
	at okio.Okio$2.read(Okio.java:140) ~[okio-1.17.4.jar!/:?]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[okio-1.17.4.jar!/:?]
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358) ~[okio-1.17.4.jar!/:?]
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230) ~[okio-1.17.4.jar!/:?]
	at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221) ~[okhttp-3.14.2.jar!/:?]
	at okhttp3.RealCall.execute(RealCall.java:81) ~[okhttp-3.14.2.jar!/:?]
	at de.tudarmstadt.ukp.inception.recommendation.imls.external.ExternalRecommender.sendRequest(ExternalRecommender.java:273) ~[inception-imls-external-0.19.2.jar!/:?]

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 0.19.2 (2021-04-07 18:54:13, build dae6182b)
 - Browser: chrome

**Comment by whisere** [comment]
It seems related to the token size too.
see below the size that works and doesn't work:
 Imported CAS with [11732] tokens and [300] sentences from file **No**

 Imported CAS with [6484] tokens and [300] sentences from file **Yes**

Imported CAS with [7996] tokens and [200] sentences from file **Yes**

**Comment by reckart** [comment]
There is currently a 30 second connect/response/transmit timeout hard-coded in `ExternalRecommender.java`. We can make that configurable though.

**Comment by whisere** [comment]
Okay Thank you! I will try change it in the file.

**Comment by whisere** [comment]
Actually I found I can't make that change as I am running from the Jar file.

**Comment by reckart** [comment]
You could try the following:
* clone the git repository
* edit the file using a text editor
* download Maven 3.6.3 from here: https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip or install it otherwise
* run `mvn -DskipTests=true clean install` at the root of the git repository
* after the build is complete, there should be a new JAR file in `inception/inception-app-webapp/target/`

**Comment by whisere** [comment]
Thank you very much, I will try it later.

**Comment by JensCardon** [comment]
@reckart 

Hello, 

Can you please provide instructions on where to set custom values for the external recommender settings? (https://github.com/inception-project/inception/blob/6008c3b341c5b8af5887c90b7623bcd4e6611cfc/inception/inception-imls-external/src/main/resources/META-INF/asciidoc/admin-guide/settings_recommendation_external.adoc)

What I already tried:
* Added a settings.properties file to my project dir .inception
* Added a recommender.properties file to .inception/repository/project/{project_id}/settings/admin
* Looked for recommender settings in the UI

For example, I want to increase the connection timeout.
<img width="1126" alt="image" src="https://github.com/inception-project/inception/assets/24375456/dc716c7a-f9c2-413f-82e0-01a63f00c1c0">

Settings don't seem to take effect when running the following command. 
java -jar inception-app-webapp-29.3-standalone.jar

What am I missing here?
Grts,
Jens

**Comment by reckart** [comment]
The settings should go to the `settings.properties`file in the INCEpTION "home" folder.

When you start up the application, the locaton of this file is logged along with an information whether INCEpTION found a file at the location or not, e.g.:

```
   _____    __  ___   __     __________  ___    __ 
  \_   \/\ \ \/ __\ /__\ __/__   \_   \/___\/\ \ \
   / /\/  \/ / /   /_\| '_ \ / /\// /\//  //  \/ /
/\/ /_/ /\  / /___//__| |_) / //\/ /_/ \_// /\  / 
\____/\_\ \/\____/\__/| .__/\/ \____/\___/\_\ \/  
                      |_|                         

2023-10-02 15:32:29 INFO [main] [SYSTEM] boot - Settings: /.../.inception/settings.properties (file exists)
```

**Comment by JensCardon** [comment]
Thanks for the fast response!
Of course I needed to set the read-timeout setting 🫠
Happy Monday!
