### ISSUE TITLE
MTAS query parser errors end up in log but not in UI

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2359]
**Describe the bug**
Lexical error at line 1, column 14. Encountered: "\\" (92), after : ""

**To Reproduce**
* Enter an invalid query into the search field
* No error in the UI
* Error in the log with stack trace

**Expected behavior**
Error shown in the UI, error in the log as well but without stack trace.

**Please complete the following information:**
 - Version and build ID: 0.19.6

**Additional context**

Document id 26336 on stable

```
Jun 09 10:53:57 blinky inception-stable.jar[12116]: mtas.parser.cql.TokenMgrError: Lexical error at line 1, column 14.  Encountered: "\\" (92), after : ""
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at mtas.parser.cql.MtasCQLParserTokenManager.getNextToken(MtasCQLParserTokenManager.java:967) ~[mtas-7.7.1.0.jar!/:7.7.1.0]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at mtas.parser.cql.MtasCQLParser.jj_scan_token(MtasCQLParser.java:2655) ~[mtas-7.7.1.0.jar!/:7.7.1.0]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at mtas.parser.cql.MtasCQLParser.jj_3_43(MtasCQLParser.java:1635) ~[mtas-7.7.1.0.jar!/:7.7.1.0]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at mtas.parser.cql.MtasCQLParser.jj_3R_16(MtasCQLParser.java:1701) ~[mtas-7.7.1.0.jar!/:7.7.1.0]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at mtas.parser.cql.MtasCQLParser.jj_3_37(MtasCQLParser.java:1991) ~[mtas-7.7.1.0.jar!/:7.7.1.0]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at mtas.parser.cql.MtasCQLParser.jj_3R_15(MtasCQLParser.java:2009) ~[mtas-7.7.1.0.jar!/:7.7.1.0]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at mtas.parser.cql.MtasCQLParser.jj_3_32(MtasCQLParser.java:2135) ~[mtas-7.7.1.0.jar!/:7.7.1.0]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at mtas.parser.cql.MtasCQLParser.jj_3R_12(MtasCQLParser.java:2164) ~[mtas-7.7.1.0.jar!/:7.7.1.0]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at mtas.parser.cql.MtasCQLParser.jj_3_27(MtasCQLParser.java:2480) ~[mtas-7.7.1.0.jar!/:7.7.1.0]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at mtas.parser.cql.MtasCQLParser.jj_3R_13(MtasCQLParser.java:2494) ~[mtas-7.7.1.0.jar!/:7.7.1.0]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at mtas.parser.cql.MtasCQLParser.jj_3R_11(MtasCQLParser.java:1765) ~[mtas-7.7.1.0.jar!/:7.7.1.0]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at mtas.parser.cql.MtasCQLParser.jj_3_5(MtasCQLParser.java:1771) ~[mtas-7.7.1.0.jar!/:7.7.1.0]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at mtas.parser.cql.MtasCQLParser.jj_2_5(MtasCQLParser.java:955) ~[mtas-7.7.1.0.jar!/:7.7.1.0]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at mtas.parser.cql.MtasCQLParser.cqlBlock(MtasCQLParser.java:136) ~[mtas-7.7.1.0.jar!/:7.7.1.0]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at mtas.parser.cql.MtasCQLParser.cql(MtasCQLParser.java:77) ~[mtas-7.7.1.0.jar!/:7.7.1.0]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at mtas.parser.cql.MtasCQLParser.parse(MtasCQLParser.java:39) ~[mtas-7.7.1.0.jar!/:7.7.1.0]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at de.tudarmstadt.ukp.inception.search.index.mtas.MtasDocumentIndex._executeQuery(MtasDocumentIndex.java:411) ~[inception-search-mtas-0.19.6.jar!/:?]Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at de.tudarmstadt.ukp.inception.search.index.mtas.MtasDocumentIndex.executeQuery(MtasDocumentIndex.java:388) ~[inception-search-mtas-0.19.6.jar!/:?]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at de.tudarmstadt.ukp.inception.search.SearchServiceImpl.query(SearchServiceImpl.java:519) ~[inception-search-core-0.19.6.jar!/:?]
Jun 09 10:53:57 blinky inception-stable.jar[12116]:         at de.tudarmstadt.ukp.inception.search.SearchServiceImpl$$FastClassBySpringCGLIB$$d6146f50.invoke(<generated>) ~[inception-search-core-0.19.6.jar!/:?]

```

**Comment by jcklie** [comment]
Maybe this is a part of #2356 . we should not log an exception when a search query is wrong
