### ISSUE TITLE
Error when trying to create a relation with a recommendation as endpoint

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2361]
**Describe the bug**

Unable to convert 'rec:296-296-4@6207' to an int value

**To Reproduce**

tbd (Kibana)

**Expected behavior**
No error

**Please complete the following information:**
 - Version and build ID: 0.19.6

**Additional context**

```
Jun 10 09:58:36 blinky inception-stable.jar[12116]: 2021-06-10 09:58:36 ERROR [redacted] BratAnnotationEditor - Error: NumberFormatException: For input string: "rec:296-296-4@6207"
Jun 10 09:58:36 blinky inception-stable.jar[12116]: org.apache.wicket.util.string.StringValueConversionException: Unable to convert 'rec:296-296-4@6207' to an int value
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.wicket.util.string.StringValue.toInt(StringValue.java:610) ~[wicket-util-9.2.0.jar!/:9.2.0]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.BratAnnotationEditor.actionArc(BratAnnotationEditor.java:480) [inception-brat-editor-0.19.6.jar!/:?]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.BratAnnotationEditor$1.respond(BratAnnotationEditor.java:270) [inception-brat-editor-0.19.6.jar!/:?]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:630) [wicket-core-9.2.0.jar!/:9.2.0]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.wicket.core.request.handler.ListenerRequestHandler.internalInvoke(ListenerRequestHandler.java:306) [wicket-core-9.2.0.jar!/:9.2.0]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.wicket.core.request.handler.ListenerRequestHandler.invoke(ListenerRequestHandler.java:280) [wicket-core-9.2.0.jar!/:9.2.0]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.wicket.core.request.handler.ListenerRequestHandler.invokeListener(ListenerRequestHandler.java:222) [wicket-core-9.2.0.jar!/:9.2.0]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.wicket.core.request.handler.ListenerRequestHandler.respond(ListenerRequestHandler.java:208) [wicket-core-9.2.0.jar!/:9.2.0]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:906) [wicket-core-9.2.0.jar!/:9.2.0]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:63) [wicket-request-9.2.0.jar!/:9.2.0]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:293) [wicket-core-9.2.0.jar!/:9.2.0]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:254) [wicket-core-9.2.0.jar!/:9.2.0]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:277) [wicket-core-9.2.0.jar!/:9.2.0]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.wicket.protocol.ws.AbstractUpgradeFilter.processRequestCycle(AbstractUpgradeFilter.java:67) [wicket-native-websocket-core-9.2.0.jar!/:9.2.0]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:208) [wicket-core-9.2.0.jar!/:9.2.0]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:307) [wicket-core-9.2.0.jar!/:9.2.0]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:186) [spring-orm-5.3.3.jar!/:5.3.3]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.3.jar!/:5.3.3]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at de.tudarmstadt.ukp.clarin.webanno.support.logging.LoggingFilter.doFilter(LoggingFilter.java:60) [inception-support-0.19.6.jar!/:?]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 10 09:58:36 blinky inception-stable.jar[12116]:         at de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.OpenCasStorageSessionForRequestFilter.doFilter(OpenCasStorageSessionForRequestFilter.java:50)
```

**Comment by reckart** [comment]
I am pretty sure this happens when one tries to create a relation between two recommendations.

**Comment by jcklie** [comment]
Should we 1) prevent that, 2) accept both or 3) print a warning and prevent it?

**Comment by reckart** [comment]
I'm going with 3. I though about 2, but... not sure about it.

**Comment by reckart** [comment]
Do you think accepting both and creating the relation would be a good idea? It is certainly a larger change. If we wanted to do that, it should be done in a separate feature request and not for the 0.19.7 release but a later one.

**Comment by jcklie** [comment]
I would go with 3, I think 2 is too surprising
