### ISSUE TITLE
NPE when exporting named entities with empty value feature as TEI

### ISSUE THREAD

**Issue by BalduinLandolt** [inception-project/inception#2461]
**Describe the bug**
NullPointerException when exporting document as TEI.

**To Reproduce**
1. Annotate document
2. Click on 'export'
3. select format 'TEI'
4. hit 'export'
5. see error

**Expected behavior**
Export document, like it works in any other format than TEI

**Screenshots**
![image](https://user-images.githubusercontent.com/33053745/124669370-90cf9400-deb2-11eb-9532-fc60524c4888.png)

**Console Output**  
(slightly shortened)
```
2021-07-06 23:30:49 ERROR [admin] PrimitiveAnalysisEngine_impl - Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException: null
        at org.dkpro.core.io.tei.TeiWriter.process(TeiWriter.java:255) ~[dkpro-core-io-tei-asl-2.2.0.jar!/:?]
        at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48) ~[uimaj-core-3.2.0.jar!/:3.2.0]
        at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.lambda$callProcessMethod$3(AnalysisEngineImplBase.java:623) ~[uimaj-core-3.2.0.jar!/:3.2.0]
        [...]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597) [tomcat-embed-core-9.0.41.jar!/:9.0.41]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.41.jar!/:9.0.41]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.41.jar!/:9.0.41]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "value" is null
        at com.ctc.wstx.sw.BaseNsStreamWriter.doWriteAttr(BaseNsStreamWriter.java:493) ~[woodstox-core-asl-4.4.1.jar!/:4.4.1]
        at com.ctc.wstx.sw.RepairingNsStreamWriter.writeAttribute(RepairingNsStreamWriter.java:125) ~[woodstox-core-asl-4.4.1.jar!/:4.4.1]
        at org.codehaus.stax2.ri.Stax2EventWriterImpl.add(Stax2EventWriterImpl.java:60) ~[stax2-api-3.1.4.jar!/:?]
        at org.codehaus.stax2.ri.Stax2EventWriterImpl.add(Stax2EventWriterImpl.java:107) ~[stax2-api-3.1.4.jar!/:?]
        at org.dkpro.core.io.tei.TeiWriter.process(TeiWriter.java:201) ~[dkpro-core-io-tei-asl-2.2.0.jar!/:?]
        ... 125 more
2021-07-06 23:30:49 ERROR [admin] ExportDocumentDialogContent - Export failed
org.apache.uima.analysis_engine.AnalysisEngineProcessException: null
        at org.dkpro.core.io.tei.TeiWriter.process(TeiWriter.java:255) ~[dkpro-core-io-tei-asl-2.2.0.jar!/:?]
        at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48) ~[uimaj-core-3.2.0.jar!/:3.2.0]
        at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.lambda$callProcessMethod$3(AnalysisEngineImplBase.java:623) ~[uimaj-core-3.2.0.jar!/:3.2.0]
        at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.withContexts(AnalysisEngineImplBase.java:640) ~[uimaj-core-3.2.0.jar!/:3.2.0]
        at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.callProcessMethod(AnalysisEngineImplBase.java:620) ~[uimaj-core-3.2.0.jar!/:3.2.0]
        [...]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888) [tomcat-embed-core-9.0.41.jar!/:9.0.41]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597) [tomcat-embed-core-9.0.41.jar!/:9.0.41]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.41.jar!/:9.0.41]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.41.jar!/:9.0.41]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "value" is null
        at com.ctc.wstx.sw.BaseNsStreamWriter.doWriteAttr(BaseNsStreamWriter.java:493) ~[woodstox-core-asl-4.4.1.jar!/:4.4.1]
        at com.ctc.wstx.sw.RepairingNsStreamWriter.writeAttribute(RepairingNsStreamWriter.java:125) ~[woodstox-core-asl-4.4.1.jar!/:4.4.1]
        at org.codehaus.stax2.ri.Stax2EventWriterImpl.add(Stax2EventWriterImpl.java:60) ~[stax2-api-3.1.4.jar!/:?]
        at org.codehaus.stax2.ri.Stax2EventWriterImpl.add(Stax2EventWriterImpl.java:107) ~[stax2-api-3.1.4.jar!/:?]
        at org.dkpro.core.io.tei.TeiWriter.process(TeiWriter.java:201) ~[dkpro-core-io-tei-asl-2.2.0.jar!/:?]
        ... 125 more
2021-07-06 23:30:49 ERROR [admin] ApplicationPageBase - admin: Export failed: NullPointerException: Cannot invoke "String.length()" because "value" is null
```

**Please complete the following information:**
 - Version and build ID: 0.19.7 (2021-06-19 00:45:41, build 53edf712)
 - OS: Windows 10
 - Browser: Same behaviour in Firefox and Edge

------

I'm not sure what causes the issue. I tried it with multiple documents, all of which had the same error occur. Here is one of the documents I tried:
[ranisch_79.txt](https://github.com/inception-project/inception/files/6772937/ranisch_79.txt)

I only added very few annotations (just playing around with the program), one of them was a reference to a custom knowledge base I added (in case that's relevant?).

I hope this helps you guys spot a bug.

**Comment by reckart** [comment]
Could you share a project export from the exports page in the project settings (format: e.g. XMI)?

**Comment by reckart** [comment]
Hm... it seems like there XMLEventFactory is creating an instance that is not compatible with the TeiWriter implementation...

**Comment by BalduinLandolt** [comment]
here is the XMI export:  
[webanno12986243084017718377export.zip](https://github.com/inception-project/inception/files/6776144/webanno12986243084017718377export.zip)

Hope this helps

**Comment by reckart** [comment]
It looks like the TEI exporter has a problem with Named Entity annotations where the "value" feature is empty. If you enter some value into the "value" feature, the TEI export should work. I'm looking into fixing this.

**Comment by BalduinLandolt** [comment]
> 
> 
> It looks like the TEI exporter has a problem with Named Entity annotations where the "value" feature is empty. If you enter some value into the "value" feature, the TEI export should work. I'm looking into fixing this.

Thanks, that's an easy enough workaround.
