### ISSUE TITLE
Deleting tokens when token-editing is enabled causes CasDoctor to bark on dev / beta versions

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#2508]
When I delete tokens, then I get

```
2021-04-11 19:16:49 ERROR [admin] CasDoctor - [AllFeatureStructuresIndexedCheck] Unindexed feature structures: 1
2021-04-11 19:16:49 ERROR [admin] CasDoctor - [AllFeatureStructuresIndexedCheck] Non-indexed feature structure [Token:1309
   sofa: _InitialView
   begin: 0
   end: 8
   parent: <null>
   lemma: <null>
   stem: <null>
   pos: <null>
   morph: <null>
   id: <null>
   form: <null>
   syntacticFunction: <null>
   order: 0] reachable through [Dependency:68854
   sofa: _InitialView
   begin: 9
   end: 17
   Governor: Token:1309
      sofa: _InitialView
      begin: 0
      end: 8
      parent: <null>
      lemma: <null>
      stem: <null>
      pos: <null>
      morph: <null>
      id: <null>
      form: <null>
      syntacticFunction: <null>
      order: 0
   Dependent: Token:1322
      sofa: _InitialView
      begin: 9
      end: 17
      parent: <null>
      lemma: <null>
      stem: <null>
      pos: <null>
      morph: <null>
      id: <null>
      form: <null>
      syntacticFunction: <null>
      order: 0
   DependencyType: <null>
   flavor: "asdf"]
2021-04-11 19:16:49 ERROR [admin] CasDoctor - [DanglingRelationsCheck] Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68854] has loose ends.
Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] attached to feature [pos].
Source: null
Target: null
2021-04-11 19:16:49 ERROR [admin] CasDoctor - [DanglingRelationsCheck] Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68862] has loose ends.
Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] attached to feature [pos].
Source: null
Target: null
2021-04-11 19:16:49 WARN [admin] RelationRenderer - Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68854] has loose ends - cannot render.
2021-04-11 19:16:49 WARN [admin] RelationRenderer - Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68862] has loose ends - cannot render.
2021-04-11 19:16:49 WARN [admin] AnnotationSchemaServiceImpl - Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68854] has loose ends - cannot identify attached annotations.
Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] attached to feature [pos].
Source: null
Target: null
2021-04-11 19:16:49 WARN [admin] AnnotationSchemaServiceImpl - Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68862] has loose ends - cannot identify attached annotations.
Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] attached to feature [pos].
Source: null
Target: null
2021-04-11 19:16:50 ERROR [admin] CasDoctor - [AllFeatureStructuresIndexedCheck] Unindexed feature structures: 1
2021-04-11 19:16:50 ERROR [admin] CasDoctor - [AllFeatureStructuresIndexedCheck] Non-indexed feature structure [Token:1309
   sofa: _InitialView
   begin: 0
   end: 8
   parent: <null>
   lemma: <null>
   stem: <null>
   pos: <null>
   morph: <null>
   id: <null>
   form: <null>
   syntacticFunction: <null>
   order: 0] reachable through [Dependency:68854
   sofa: _InitialView
   begin: 9
   end: 17
   Governor: Token:1309
      sofa: _InitialView
      begin: 0
      end: 8
      parent: <null>
      lemma: <null>
      stem: <null>
      pos: <null>
      morph: <null>
      id: <null>
      form: <null>
      syntacticFunction: <null>
      order: 0
   Dependent: Token:1322
      sofa: _InitialView
      begin: 9
      end: 17
      parent: <null>
      lemma: <null>
      stem: <null>
      pos: <null>
      morph: <null>
      id: <null>
      form: <null>
      syntacticFunction: <null>
      order: 0
   DependencyType: <null>
   flavor: "asdf"]
2021-04-11 19:16:50 ERROR [admin] CasDoctor - [DanglingRelationsCheck] Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68854] has loose ends.
Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] attached to feature [pos].
Source: null
Target: null
2021-04-11 19:16:50 ERROR [admin] CasDoctor - [DanglingRelationsCheck] Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68862] has loose ends.
Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] attached to feature [pos].
Source: null
Target: null
2021-04-11 19:16:50 WARN [admin] AnnotationSchemaServiceImpl - Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68854] has loose ends - cannot identify attached annotations.
Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] attached to feature [pos].
Source: null
Target: null
2021-04-11 19:16:50 WARN [admin] AnnotationSchemaServiceImpl - Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68862] has loose ends - cannot identify attached annotations.
Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] attached to feature [pos].
Source: null
Target: null
2021-04-11 19:16:50 WARN [admin] AnnotationSchemaServiceImpl - Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68854] has loose ends - cannot identify attached annotations.
Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] attached to feature [pos].
Source: null
Target: null
2021-04-11 19:16:50 WARN [admin] AnnotationSchemaServiceImpl - Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68862] has loose ends - cannot identify attached annotations.
Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] attached to feature [pos].
Source: null
Target: null
2021-04-11 19:16:50 ERROR [admin] CasDoctor - [AllFeatureStructuresIndexedCheck] Unindexed feature structures: 1
2021-04-11 19:16:50 ERROR [admin] CasDoctor - [AllFeatureStructuresIndexedCheck] Non-indexed feature structure [Token:1309
   sofa: _InitialView
   begin: 0
   end: 8
   parent: <null>
   lemma: <null>
   stem: <null>
   pos: <null>
   morph: <null>
   id: <null>
   form: <null>
   syntacticFunction: <null>
   order: 0] reachable through [Dependency:68854
   sofa: _InitialView
   begin: 9
   end: 17
   Governor: Token:1309
      sofa: _InitialView
      begin: 0
      end: 8
      parent: <null>
      lemma: <null>
      stem: <null>
      pos: <null>
      morph: <null>
      id: <null>
      form: <null>
      syntacticFunction: <null>
      order: 0
   Dependent: Token:1322
      sofa: _InitialView
      begin: 9
      end: 17
      parent: <null>
      lemma: <null>
      stem: <null>
      pos: <null>
      morph: <null>
      id: <null>
      form: <null>
      syntacticFunction: <null>
      order: 0
   DependencyType: <null>
   flavor: "asdf"]
2021-04-11 19:16:50 ERROR [admin] CasDoctor - [DanglingRelationsCheck] Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68854] has loose ends.
Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] attached to feature [pos].
Source: null
Target: null
2021-04-11 19:16:50 ERROR [admin] CasDoctor - [DanglingRelationsCheck] Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68862] has loose ends.
Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] attached to feature [pos].
Source: null
Target: null
2021-04-11 19:16:50 WARN [admin] RelationRenderer - Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68854] has loose ends - cannot render.
2021-04-11 19:16:50 WARN [admin] RelationRenderer - Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68862] has loose ends - cannot render.
2021-04-11 19:16:50 WARN [admin] ApplicationPageBase - admin: Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68854] has loose ends - cannot render.
Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] attached to feature [pos].
Dependent: null
Governor: null
2021-04-11 19:16:50 WARN [admin] ApplicationPageBase - admin: Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68862] has loose ends - cannot render.
Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] attached to feature [pos].
Dependent: null
Governor: null
2021-04-11 19:16:50 WARN [admin] ApplicationPageBase - admin: Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68854] has loose ends - cannot render.
Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] attached to feature [pos].
Dependent: null
Governor: null
2021-04-11 19:16:50 WARN [admin] ApplicationPageBase - admin: Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] with id [68862] has loose ends - cannot render.
Relation [de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency] attached to feature [pos].
Dependent: null
Governor: null
2021-04-11 19:16:50 INFO [admin] ApplicationPageBase - admin: The [Token] annotation has been deleted.
2021-04-11 19:16:50 ERROR [SYSTEM] MtasUimaParser - Unable to create token collection
java.lang.NullPointerException: null
	at de.tudarmstadt.ukp.inception.search.index.mtas.MtasUimaParser.getRange(MtasUimaParser.java:248) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.search.index.mtas.MtasUimaParser.indexAnnotation(MtasUimaParser.java:318) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.search.index.mtas.MtasUimaParser.createTokenCollection(MtasUimaParser.java:235) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.search.index.mtas.MtasUimaParser.createTokenCollection(MtasUimaParser.java:189) [classes/:?]
	at mtas.analysis.MtasTokenizer.constructTokenCollection(MtasTokenizer.java:237) [mtas-7.7.1.0.jar:7.7.1.0]
	at mtas.analysis.MtasTokenizer.reset(MtasTokenizer.java:171) [mtas-7.7.1.0.jar:7.7.1.0]
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:789) [lucene-core-7.7.3.jar:7.7.3 1a0d2a901dfec93676b0fe8be425101ceb754b85 - noble - 2020-04-21 10:31:55]
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:430) [lucene-core-7.7.3.jar:7.7.3 1a0d2a901dfec93676b0fe8be425101ceb754b85 - noble - 2020-04-21 10:31:55]
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:394) [lucene-core-7.7.3.jar:7.7.3 1a0d2a901dfec93676b0fe8be425101ceb754b85 - noble - 2020-04-21 10:31:55]
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:251) [lucene-core-7.7.3.jar:7.7.3 1a0d2a901dfec93676b0fe8be425101ceb754b85 - noble - 2020-04-21 10:31:55]
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:494) [lucene-core-7.7.3.jar:7.7.3 1a0d2a901dfec93676b0fe8be425101ceb754b85 - noble - 2020-04-21 10:31:55]
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1616) [lucene-core-7.7.3.jar:7.7.3 1a0d2a901dfec93676b0fe8be425101ceb754b85 - noble - 2020-04-21 10:31:55]
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1235) [lucene-core-7.7.3.jar:7.7.3 1a0d2a901dfec93676b0fe8be425101ceb754b85 - noble - 2020-04-21 10:31:55]
	at de.tudarmstadt.ukp.inception.search.index.mtas.MtasDocumentIndex.indexDocument(MtasDocumentIndex.java:913) [classes/:?]
	at de.tudarmstadt.ukp.inception.search.index.mtas.MtasDocumentIndex.indexDocument(MtasDocumentIndex.java:1134) [classes/:?]
	at de.tudarmstadt.ukp.inception.search.SearchServiceImpl.indexDocument(SearchServiceImpl.java:473) [classes/:?]
	at de.tudarmstadt.ukp.inception.search.SearchServiceImpl.indexDocument(SearchServiceImpl.java:426) [classes/:?]
	at de.tudarmstadt.ukp.inception.search.SearchServiceImpl$$FastClassBySpringCGLIB$$d6146f50.invoke(<generated>) [classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) [spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) [spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) [spring-tx-5.3.3.jar:5.3.3]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) [spring-tx-5.3.3.jar:5.3.3]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) [spring-tx-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) [spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) [spring-aop-5.3.3.jar:5.3.3]
	at de.tudarmstadt.ukp.inception.search.SearchServiceImpl$$EnhancerBySpringCGLIB$$f786646f.indexDocument(<generated>) [classes/:?]
	at de.tudarmstadt.ukp.inception.search.scheduling.tasks.IndexAnnotationDocumentTask.run(IndexAnnotationDocumentTask.java:47) [classes/:?]
	at de.tudarmstadt.ukp.inception.search.scheduling.TaskConsumer.run(TaskConsumer.java:70) [classes/:?]
	at java.lang.Thread.run(Thread.java:853) [?:?]

```

_Originally posted by @jcklie in https://github.com/inception-project/inception/issues/2141#issuecomment-817341063_

**Comment by reckart** [comment]
No longer an issue.
