### ISSUE TITLE
Cannot export project when curation started

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#2541]
**Describe the bug**
Trying to export a project that contains a document(s) that has been opened for curation results in an error:

<details>

```

2021-08-12 15:43:36 ERROR [admin] ProjectExportFullProjectTask - Unexpected error during project export
java.io.IOException: de.tudarmstadt.ukp.clarin.webanno.api.casstorage.CasSessionException: No CAS storage session available
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.CasStorageServiceImpl.existsCas(CasStorageServiceImpl.java:814) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.CasStorageServiceImpl$$FastClassBySpringCGLIB$$70b0ffa.invoke(<generated>) ~[classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.8.jar:5.3.8]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.3.8.jar:5.3.8]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.CasStorageServiceImpl$$EnhancerBySpringCGLIB$$fb9dc9eb.existsCas(<generated>) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.DocumentServiceImpl.existsCas(DocumentServiceImpl.java:236) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.DocumentServiceImpl$$FastClassBySpringCGLIB$$7e8e7e07.invoke(<generated>) ~[classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.8.jar:5.3.8]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.3.8.jar:5.3.8]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.DocumentServiceImpl$$EnhancerBySpringCGLIB$$38615b46.existsCas(<generated>) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.exporters.CuratedDocumentsExporter.exportData(CuratedDocumentsExporter.java:125) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl.exportProject(ProjectExportServiceImpl.java:230) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl.exportProject(ProjectExportServiceImpl.java:174) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl$$FastClassBySpringCGLIB$$3d43e16f.invoke(<generated>) ~[classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.8.jar:5.3.8]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.8.jar:5.3.8]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.8.jar:5.3.8]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.8.jar:5.3.8]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.8.jar:5.3.8]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.8.jar:5.3.8]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.8.jar:5.3.8]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar:5.3.8]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.8.jar:5.3.8]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.8.jar:5.3.8]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl$$EnhancerBySpringCGLIB$$31e84f6a.exportProject(<generated>) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportFullProjectTask.export(ProjectExportFullProjectTask.java:46) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportTask_ImplBase.run(ProjectExportTask_ImplBase.java:79) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: de.tudarmstadt.ukp.clarin.webanno.api.casstorage.CasSessionException: No CAS storage session available
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.CasStorageSession.get(CasStorageSession.java:141) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.CasStorageServiceImpl$WithExclusiveAccess.<init>(CasStorageServiceImpl.java:835) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.CasStorageServiceImpl.existsCas(CasStorageServiceImpl.java:807) ~[classes/:?]
	... 31 more
2021-08-12 15:43:38 ERROR [admin] ApplicationPageBase - admin: Unexpected error during project export: CasSessionException: No CAS storage session available
2021-08-12 15:43:38 ERROR [admin] ApplicationPageBase - admin: Project export failed

```

</details>

**To Reproduce**
1. Open a document on the curation page
2. Export the project on the settings -> export tab

**Please complete the following information:**
 - Version and build ID: 0.21.0-SNAPSHOT (not in 20.x)
 - OS: Linux
 - Browser: Chrome

**Comment by reckart** [comment]
Is 20.x affected?
