### ISSUE TITLE
Problem with string feature editor initialization

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#2567]
Sometimes (not every time) the dropdown for feature values has problems showing the shadow on only the value that the mouse is hovering over and the description of the feature value is at a weird place (see image)

![](https://user-images.githubusercontent.com/29500351/130026540-c6258ef0-356f-4f69-8412-2d008608dac9.png)

**Comment by reckart** [comment]
@UWinch I have trouble reproducing this problem that you had originally reported on Upgrade to Bootstrap 5 #2475. Can you reproduce it? Do you see any errors in the JS console when this happens?

**Comment by UWinch** [comment]
I get this problem after having opened a sidebar (e.g. the search sidebar). The console shows this warning, however, I'm not sure if it is related:

```

Rendering terminated due to: IndexSizeError: Failed to execute 'getEndPositionOfChar' on 'SVGTextContentElement': The charnum provided (5) is greater than the maximum bound (0). Error: Failed to execute 'getEndPositionOfChar' on 'SVGTextContentElement': The charnum provided (5) is greater than the maximum bound (0).
    at Visualizer.calculateSubstringWidthFast (http://localhost:8080/inception-app-webapp/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer.js:2081:16)
    at http://localhost:8080/inception-app-webapp/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer.js:1948:37
    at Fragment.<anonymous> (http://localhost:8080/inception-app-webapp/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer.js:1854:13)
    at Function.each (http://localhost:8080/inception-app-webapp/wicket/resource/org.apache.wicket.resource.JQueryResourceReference/jquery/jquery-2.2.4.js:365:19)
    at SVGTextElement.<anonymous> (http://localhost:8080/inception-app-webapp/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer.js:1853:13)
    at Function.each (http://localhost:8080/inception-app-webapp/wicket/resource/org.apache.wicket.resource.JQueryResourceReference/jquery/jquery-2.2.4.js:365:19)
    at jQuery.fn.init.each (http://localhost:8080/inception-app-webapp/wicket/resource/org.apache.wicket.resource.JQueryResourceReference/jquery/jquery-2.2.4.js:137:17)
    at Visualizer.getTextMeasurements (http://localhost:8080/inception-app-webapp/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer.js:1848:40)
    at Visualizer.calculateChunkTextMeasures (http://localhost:8080/inception-app-webapp/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer.js:1894:19)
    at Visualizer.calculateTextMeasurements (http://localhost:8080/inception-app-webapp/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer.js:1868:30)
rerender @ visualizer.js:4174
(anonymous) @ dispatcher.js:130
each @ jquery-2.2.4.js:365
post @ dispatcher.js:119
resizeFunction @ visualizer_ui.js:911

```

**Comment by reckart** [comment]
What browser/version are you using?

**Comment by UWinch** [comment]
Chrome 92.0.4515.107 or Firefox 91.0.2

**Comment by reckart** [comment]
And you get the index size issue also in Chrome or only in Firefox?
