### ISSUE TITLE
IndexOutOfBoundsException in BratRenderer.trim 

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#2629]
**Describe the bug**
`StringIndexOutOfBoundsException` in `BratRenderer.trim(...)`

This happens with the *brat (wrapping @ 120 chars)* setting and a very large page size (500).

**To Reproduce**
Found in logs:

```
ERROR BratAnnotationEditor - Error: StringIndexOutOfBoundsException: String index out of range: 7206
java.lang.StringIndexOutOfBoundsException: String index out of range: 7206
        at java.lang.StringLatin1.charAt(StringLatin1.java:48) ~[?:?]
        at java.lang.String.charAt(String.java:712) ~[?:?]
        at de.tudarmstadt.ukp.clarin.webanno.brat.render.BratRenderer.trim(BratRenderer.java:644) ~[inception-brat-editor-21.0-rc-1.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.brat.render.BratRenderer.split(BratRenderer.java:451) ~[inception-brat-editor-21.0-rc-1.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.brat.render.BratRenderer.renderBratTokensFromText(BratRenderer.java:361) ~[inception-brat-editor-21.0-rc-1.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.brat.render.BratRenderer.render(BratRenderer.java:153) ~[inception-brat-editor-21.0-rc-1.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.brat.render.BratRenderer.render(BratRenderer.java:120) ~[inception-brat-editor-21.0-rc-1.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.BratAnnotationEditor.render(BratAnnotationEditor.java:659) ~[inception-brat-editor-21.0-rc-1.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.BratAnnotationEditor.actionGetDocument(BratAnnotationEditor.java:457) [inception-brat-editor-21.0-rc-1.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.BratAnnotationEditor$1.respond(BratAnnotationEditor.java:256) [inception-brat-editor-21.0-rc-1.jar!/:?]
        at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:630) [wicket-core-9.4.0.jar!/:9.4.0]
```

**Expected behavior**
No error.

**Please complete the following information:**
 - Version and build ID: 21.0-rc-1

**Comment by reckart** [comment]
Looks like it might be an error in the data - apparently an end offset that is larger than the document text.

<img width="640" alt="Screenshot 2021-09-28 at 09 17 00" src="https://user-images.githubusercontent.com/1410238/135041085-68248790-01ca-481b-8a42-98221f0f87fd.png">

**Comment by reckart** [comment]
Looks like the problem was that the text that was passed in was only a substring of the visible text instead of the whole visible text, so the offsets were way off.
