### ISSUE TITLE
ReferenceError: fragment is not defined 

### ISSUE THREAD

**Issue by Kentoseth** [inception-project/inception#2653]
**Describe the bug**
When I annotate a word using the POS layer, after selecting the word, the screen goes blank minus a thin blue line. See screenshot:

![bug](https://user-images.githubusercontent.com/2989402/137632921-9f3ecd83-c50b-42c1-b4f2-cb1576420c3b.png)

Version: inception-app-webapp-21.0.1-standalone.jar
OS: Ubuntu 20.04(container)

**To Reproduce**
1. Start Inception: `java -Djava.awt.headless=true -Dserver.port=8999 -Dserver.ip=0.0.0.0 -jar inception-app-webapp-21.0.1-standalone.jar`
2. Create project with attached file(file can't be attached, so create hadith1.txt with this string: `النِّساءُ حَبائِلُ الشَيْطانِ`)
3. Go to Annotate, try to add POS layer, bug happens in both Firefox and Brave.
4. No error in app-log, but error is found in browser-tools. Pasting below:

```
Rendering terminated due to: ReferenceError: fragment is not defined 
calculateSubstringWidthRobust@http://10.0.3.48:8999/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-61D190B4DEBE18B2C29B4672DFCB97F8.js:1539:5
calculateChunkTextMeasures/Visualizer<@http://10.0.3.48:8999/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-61D190B4DEBE18B2C29B4672DFCB97F8.js:1513:28
getTextMeasurements/</<@http://10.0.3.48:8999/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-61D190B4DEBE18B2C29B4672DFCB97F8.js:1443:9
each@http://10.0.3.48:8999/wicket/resource/org.apache.wicket.resource.JQueryResourceReference/jquery/jquery-2.2.4-ver-F9EE266EF993962AD59E804AD9DEBE66.js:2:2861
getTextMeasurements/<@http://10.0.3.48:8999/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-61D190B4DEBE18B2C29B4672DFCB97F8.js:1442:3
each@http://10.0.3.…
visualizer-ver-61D190B4DEBE18B2C29B4672DFCB97F8.js:3420:9
    renderData http://10.0.3.48:8999/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-61D190B4DEBE18B2C29B4672DFCB97F8.js:3420
    (Async: setTimeout handler)
    renderData http://10.0.3.48:8999/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-61D190B4DEBE18B2C29B4672DFCB97F8.js:3414
    post http://10.0.3.48:8999/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratDispatcherResourceReference/dispatcher-ver-B99CA8F8CFB68625E75A99A6A27AA1DF.js:89
    each jQuery
    post http://10.0.3.48:8999/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratDispatcherResourceReference/dispatcher-ver-B99CA8F8CFB68625E75A99A6A27AA1DF.js:78
    <anonymous> http://10.0.3.48:8999/p/zaad/annotate/?14#!d=0&f=1 line 1 > injectedScript:1
    <anonymous> http://10.0.3.48:8999/p/zaad/annotate/?14#!d=0&f=1 line 1 > injectedScript:1
    jQuery 45
    ajaxCall http://10.0.3.48:8999/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratAjaxResourceReference/ajax-ver-FCB474B61313C44E6BE1FCAA984E0CD4.js:26
    post http://10.0.3.48:8999/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratDispatcherResourceReference/dispatcher-ver-B99CA8F8CFB68625E75A99A6A27AA1DF.js:89
```

**Expected behavior**
POS tag to work and not give this error.

**Screenshots**
See above.

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 21.0.1 (2021-10-11 23:50:35, build db19cae9) 
 - OS: Ubuntu 20.04
 - Browser: Firefox and Brave

**Additional context**
This is a RtL language. I tested with other layers and the same error occurs.

**Comment by Kentoseth** [comment]
> Could you please try in Chrome?

I use Brave, which has the same rendering engine as Chrome. The browser error-output from it is:

```
visualizer-ver-61D190B4DEBE18B2C29B4672DFCB97F8.js:3420 Rendering terminated due to: ReferenceError: fragment is not defined ReferenceError: fragment is not defined
    at Visualizer.calculateSubstringWidthRobust (http://10.0.3.48:8999/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-61D190B4DEBE18B2C29B4672DFCB97F8.js:1539:1)
    at http://10.0.3.48:8999/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-61D190B4DEBE18B2C29B4672DFCB97F8.js:1513:28
    at Fragment.<anonymous> (http://10.0.3.48:8999/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-61D190B4DEBE18B2C29B4672DFCB97F8.js:1443:1)
    at Function.each (http://10.0.3.48:8999/wicket/resource/org.apache.wicket.resource.JQueryResourceReference/jquery/jquery-2.2.4-ver-F9EE266EF993962AD59E804AD9DEBE66.js:2:2861)
    at SVGTextElement.<anonymous> (http://10.0.3.48:8999/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-61D190B4DEBE18B2C29B4672DFCB97F8.js:1442:3)
    at Function.each (http://10.0.3.48:8999/wicket/resource/org.apache.wicket.resource.JQueryResourceReference/jquery/jquery-2.2.4-ver-F9EE266EF993962AD59E804AD9DEBE66.js:2:2861)
    at n.fn.init.each (http://10.0.3.48:8999/wicket/resource/org.apache.wicket.resource.JQueryResourceReference/jquery/jquery-2.2.4-ver-F9EE266EF993962AD59E804AD9DEBE66.js:2:845)
    at Visualizer.getTextMeasurements (http://10.0.3.48:8999/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-61D190B4DEBE18B2C29B4672DFCB97F8.js:1438:34)
    at Visualizer.calculateChunkTextMeasures (http://10.0.3.48:8999/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-61D190B4DEBE18B2C29B4672DFCB97F8.js:1475:13)
    at Visualizer.calculateTextMeasurements (http://10.0.3.48:8999/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-61D190B4DEBE18B2C29B4672DFCB97F8.js:1453:24)
```

I can try in Chrome, but would prefer not to use it because of its binary blobs.

**Comment by reckart** [comment]
Ok. No problem. Firefox and Chrome-based browsers use a different branch in some RTL code, that is why I asked. Thanks for reporting, I'll look into it.
