### ISSUE TITLE
pycaprio - problem of uploading annotation

### ISSUE THREAD

**Issue by WilliamQue** [inception-project/inception#2857]
I download annotation info with CTSV3 format and then upload it by pycaprio , 
```
client = Pycaprio("http://remote1:18080", authentication=("admin", "pass"))

# annotation download
annotation_content = client.api.annotation(1, 4, 'admin', annotation_format=InceptionFormat.CTSV3)
with open('anno_text', 'wb') as annotation_file:
    annotation_file.write(annotation_content)

# annotation upload
with open("anno_text", 'rb') as annotation_file:
    new_annotation = client.api.create_annotation(1, 4, 'admin', annotation_file,
                                                  annotation_format=InceptionFormat.CTSV3, annotation_state=AnnotationState.IN_PROGRESS)
```

python will report when uploading anno_text:
```
Traceback (most recent call last):
  File "D:\miniconda3\envs\nlp38\lib\site-packages\tenacity\__init__.py", line 362, in call
    result = fn(*args, **kwargs)
  File "D:\miniconda3\envs\nlp38\lib\site-packages\pycaprio\core\clients\retryable_client.py", line 66, in _request
    raise RetryableException(response)
pycaprio.core.clients.exceptions.RetryableException
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "D:\miniconda3\envs\nlp38\lib\site-packages\pycaprio\core\clients\retryable_client.py", line 48, in request
    return self._request(method, url, allowed_statuses, **kwargs)
  File "D:\miniconda3\envs\nlp38\lib\site-packages\tenacity\__init__.py", line 293, in wrapped_f
    return self.call(f, *args, **kw)
  File "D:\miniconda3\envs\nlp38\lib\site-packages\tenacity\__init__.py", line 359, in call
    do = self.iter(retry_state=retry_state)
  File "D:\miniconda3\envs\nlp38\lib\site-packages\tenacity\__init__.py", line 333, in iter
    six.raise_from(retry_exc, fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x1a9bd403d60 state=finished raised RetryableException>]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\miniconda3\envs\nlp38\lib\site-packages\IPython\core\interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-f88d932a7f9b>", line 3, in <module>
    new_annotation = client.api.create_annotation(1, 4, 'william', annotation_file,
  File "D:\miniconda3\envs\nlp38\lib\site-packages\pycaprio\core\adapters\http_adapter.py", line 100, in create_annotation
    response = self.client.post(f"/projects/{project_id}/documents/{document_id}/annotations/{user_name}",
  File "D:\miniconda3\envs\nlp38\lib\site-packages\pycaprio\core\clients\retryable_client.py", line 40, in post
    return self.request('post', url, allowed_statuses, data=data, json=json, files=files)
  File "D:\miniconda3\envs\nlp38\lib\site-packages\pycaprio\core\clients\retryable_client.py", line 50, in request
    raise InceptionBadResponse(retry_error.last_attempt._exception.bad_response)
pycaprio.core.exceptions.InceptionBadResponse
```

I'll do something between download and upload, for example, modifying anno_text to add more annotation the uploading it, now nothing can be done.

Environment:
Inception 22.3 on Centos 7.9
Python 3.8 on win 10
pycaprio 0.20 / 0.21

**Comment by reckart** [comment]
Do you see any exception in the INCEpTION server logs?

**Comment by WilliamQue** [comment]
2022-02-14 19:25:31 ERROR [admin] AeroRemoteApiController - Line does not start with expected prefix [#FORMAT=]: [null]
java.io.IOException: Line does not start with expected prefix [#FORMAT=]: [null]
	at de.tudarmstadt.ukp.clarin.webanno.tsv.internal.tsv3x.Tsv3XDeserializer.expectStartsWith(Tsv3XDeserializer.java:911) ~[inception-io-webanno-tsv-22.3.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.tsv.internal.tsv3x.Tsv3XDeserializer.readFormat(Tsv3XDeserializer.java:183) ~[inception-io-webanno-tsv-22.3.jar!/:?]
......

**Comment by reckart** [comment]
What does  the `anno_text` file start with content-wise?

**Comment by WilliamQue** [comment]
#FORMAT=WebAnno TSV 3.3
#T_SP=webanno.custom.Correction|correction_features

**Comment by WilliamQue** [comment]
more log info:

2022-02-14 22:51:58 INFO [admin] WebannoTsv3XReader - Scanning [file:/tmp/]
2022-02-14 22:51:58 INFO [admin] WebannoTsv3XReader - Found [1] resources to be read
2022-02-14 22:51:58 INFO [admin] WebannoTsv3XReader - 0 of 1: file:/tmp/upload1273156179975168655.bin
2022-02-14 22:51:58 ERROR [admin] AeroRemoteApiController - Line does not start with expected prefix [#FORMAT=]: [null]
java.io.IOException: Line does not start with expected prefix [#FORMAT=]: [null]

**Comment by reckart** [comment]
So it seems as if pycaprio is sending an empty file. I just have had to fight with something similar trying to use pycaprio but with a different format. So what I think happens is this. Pycaprio has some strange habit of trying to re-do a request several times if if fails. This causes multiple errors to be logged on the server side. Only the first of these errors is the real error. The other errors are strange `null` type errors like you have seen it. Re-try your script and watch the log - find the first error that is logged - it is most likely a different one than `[#FORMAT=]: [null]` - if the error you find doesn't tell you what's going on, post it here so we can have a look.

**Comment by reckart** [comment]
There is even a related issue already since some time: https://github.com/JavierLuna/pycaprio/issues/5

**Comment by WilliamQue** [comment]
The following codes are still in problem. 
Is pycaprio out of mantainance?  the last version came In may, 2020, almost one and a half year ago, but Inception almost releases a new version every a half month.

Is there a way to do the same thing as pycaprio,?  pure Java?

```
annotation_content = client.api.annotation(1, 4, 'admin', annotation_format=InceptionFormat.XMI)
with open(filename, 'wb') as annotation_file:
    annotation_file.write(annotation_content)

with open(filename, 'rb') as f:
    cas = load_cas_from_xmi(f)
```

**Comment by reckart** [comment]
The remote API of INCEpTION has not changed for a very long time, so strictly speaking an update for the client wouldn't be necessary. I have pinged Javier in the issue linked above how we should proceed with the retry issue - maybe he'll reply. 

The present remote API largely conforms to the OpenMinTeD AREO protocol: https://openminted.github.io/releases/aero-spec/1.0.0/omtd-aero/

There is no Java client library for it around (in the unit tests we do direct HTTP calls), but it shouldn't be difficult to write one. There's also the Swagger UI in INCEpTION where you can easily try out calls.

**Comment by reckart** [comment]
When you obtain a document in XMI format, what you get back is not an XMI file but a ZIP file containing the XMI and the type system file necessary to parse the XMI. You can do it like this:

```
    with TemporaryDirectory() as tmpdir:
        with ZipFile(BytesIO(pycaprio.api.annotation(1, 4, annotation_format=InceptionFormat.XMI))) as xmi_zip:
            type_system = load_typesystem(BytesIO(xmi_zip.read('TypeSystem.xml')))
            for i in xmi_zip.filelist:
                if i.filename.endswith('.xmi'):
                    cas = load_cas_from_xmi(BytesIO(xmi_zip.read(i)), typesystem=type_system)
                    break # There is only one XMI per ZIP
    print(cas.sofa_string)
```

**Comment by JavierLuna** [comment]
Still need to test against a server, but I think I've already fixed it: https://github.com/JavierLuna/pycaprio/tree/pycaprio-5

I'll try to add integs to ease up the dev speed this weekend too, sorry for the delay
