### ISSUE TITLE
Large data size project zip import via REST API: MaxUploadSizeExceededException

### ISSUE THREAD

**Issue by GiantEnemyCrab** [inception-project/inception#3061]
When importing large project zip file (mine was around 280MB), it was not successful due to MaxUploadSizeExceededException.
I was curious what would be a nice work-around for this.

I used a command line like below, as hinted by REST API page from INCEpTION (swagger-ui.html)
This is a test instance of the application, so default admin user is used, and `my_project_name.zip` below is the one that had about 280MB, which exported without an issue using REST API.
```
curl -su admin -iL -X 'POST' 'http://localhost:8080/api/aero/v1/projects/import' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'file=@my_project_name.zip;type=application/zip'
```

Error log
```
ERROR [SYSTEM] [dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested excepti
on is org.springframework.web.multipart.MaxUploadSizeExceededException: Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileup
load.impl.SizeLimitExceededException: the request was rejected because its size (302572161) exceeds the configured maximum (104857600)] with root cause                                      
org.apache.tomcat.util.http.fileupload.impl.SizeLimitExceededException: the request was rejected because its size (302572161) exceeds the configured maximum (104857600)                     
        at org.apache.tomcat.util.http.fileupload.impl.FileItemIteratorImpl.init(FileItemIteratorImpl.java:161) ~[tomcat-embed-core-9.0.62.jar!/:?]                                          
        at org.apache.tomcat.util.http.fileupload.impl.FileItemIteratorImpl.getMultiPartStream(FileItemIteratorImpl.java:205) ~[tomcat-embed-core-9.0.62.jar!/:?]                            
        at org.apache.tomcat.util.http.fileupload.impl.FileItemIteratorImpl.findNextItem(FileItemIteratorImpl.java:224) ~[tomcat-embed-core-9.0.62.jar!/:?]                                  
        at org.apache.tomcat.util.http.fileupload.impl.FileItemIteratorImpl.<init>(FileItemIteratorImpl.java:142) ~[tomcat-embed-core-9.0.62.jar!/:?]                                        
        at org.apache.tomcat.util.http.fileupload.FileUploadBase.getItemIterator(FileUploadBase.java:252) ~[tomcat-embed-core-9.0.62.jar!/:?]                                                
        at org.apache.tomcat.util.http.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:276) ~[tomcat-embed-core-9.0.62.jar!/:?]                                                   
        at org.apache.catalina.connector.Request.parseParts(Request.java:2932) ~[tomcat-embed-core-9.0.62.jar!/:?]                                                                           
        at org.apache.catalina.connector.Request.getParts(Request.java:2834) ~[tomcat-embed-core-9.0.62.jar!/:?]                                                                             
        at org.apache.catalina.connector.RequestFacade.getParts(RequestFacade.java:1098) ~[tomcat-embed-core-9.0.62.jar!/:?]                                                                 
        at javax.servlet.http.HttpServletRequestWrapper.getParts(HttpServletRequestWrapper.java:361) ~[tomcat-embed-core-9.0.62.jar!/:4.0.1]                                                 
        at javax.servlet.http.HttpServletRequestWrapper.getParts(HttpServletRequestWrapper.java:361) ~[tomcat-embed-core-9.0.62.jar!/:4.0.1]                                                 
        at javax.servlet.http.HttpServletRequestWrapper.getParts(HttpServletRequestWrapper.java:361) ~[tomcat-embed-core-9.0.62.jar!/:4.0.1]
```

**Comment by reckart** [comment]
Try setting `spring.servlet.multipart.max-file-size` and `spring.servlet.multipart.max-request-size` to a larger number, e.g. `500MB` in your `settings.properties`.

**Comment by GiantEnemyCrab** [comment]
Thanks so much! It worked!
I didn't imagine`settings.properties` to be also the place to add Spring-related configuration, but that was easy to add.

A side question, does REST API have "create missing users" and "import permissions"? I see these options from project import GUI, I didn't see that as a parameter in swagger view.

**Comment by reckart** [comment]
No, those currently do not exist as options. When you import viat the remote API, it uses `createMissingUsers=false` and `importPermissions=true` implicitly.

**Comment by GiantEnemyCrab** [comment]
Thanks again on this, and I guess if I really wanted to make the createMissingUsers to be always true, I suppose I could change `AeroRemoteApiController.java`'s `ProjectImportRequest(false)` to `(ProjectImportRequest(true)`. And I consider this Github issue to be resolved.

**Comment by reckart** [comment]
You could, but why would you want to turn on the option? Missing users are created as disabled users. They won't be able to do anything unless an admin enables them explicitly through the UI. What is your use-case?

**Comment by GiantEnemyCrab** [comment]
If I export an project from one instance of INCEpTION to another, and maybe this is for testing things out.

If this another server does not have these missing users, I am not able to see curation of these documents because of the missing users. For example, if all the annotators for the particular document are the missing users in another instance of INCEpTION.

**Comment by reckart** [comment]
Ok. Normally, I would expect that "for testing" you'd probably rather use the UI anyway where the option is available. But if you have a setup where it is more convenient for you to do it via the remote API, ok.

Adding a parameter to enable the creation of missing users to the import endpoint is not a breaking change - and it is a trivial addition in INCEpTION. I don't know though if pycaprio can transparently pass new parameters through to INCEpTION or if a change would be required there too (that is if you use pycaprio).

**Comment by GiantEnemyCrab** [comment]
I haven't used `pycaprio`, though I have looked at it.

Back in Feb 2022 when I worked on the technology transition, `pycaprio` still had ownership transfer in-progress to be able to push the latest updates into pypi.org, which made me worried if any future updates would be available in pypi. So, I kept using the internally developed Webanno remote API wrapper from before, which didn't need much change.

I am seeing that `pycaprio`'s newest version is available as seen in https://pypi.org/project/pycaprio/#history, with version 0.2.1 from March 2022.

If a change is needed, I guess the maintainer of `pycaprio` could change and also update the version. I am not sure if new parameters would be automatically passable either.

This is a fairly minor and not a critical change, though always nice to mirror all the options available in UI in the remote API.

And for additional context, the reason why I cannot use UI in most cases for project import is due to sensitive data needing to be stored in server, and not downloaded to local. And I wouldn't go through the processes of attempting to mount S3 bucket (where the data is stored) on Mac.

**Comment by robatwilliams** [comment]
> Try setting `spring.servlet.multipart.max-file-size` and `spring.servlet.multipart.max-request-size` to a larger number, e.g. `500MB` in your `settings.properties`.

I also had to set `server.tomcat.max-http-form-post-size` and `server.tomcat.max-swallow-size`.
