### ISSUE TITLE
NPE when using recommenders on NE with a value but no identifier

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#307]
![2018-06-20_12-05-53](https://user-images.githubusercontent.com/1410238/41652019-4d2c288c-7482-11e8-9560-971389918eb9.png)

```
2018-06-20 12:04:17 ERROR [SYSTEM] TaskConsumer - PredictionTask [project=INCEpTION Paper, user=admin] failed.
java.lang.NullPointerException: null
	at de.tudarmstadt.ukp.inception.recommendation.api.Classifier.mergeAdjacentTokensWithSameLabel(Classifier.java:115) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.recommendation.api.Classifier.predict(Classifier.java:72) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.recommendation.scheduling.tasks.PredictionTask.lambda$0(PredictionTask.java:103) ~[classes/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_144]
	at de.tudarmstadt.ukp.inception.recommendation.scheduling.tasks.PredictionTask.run(PredictionTask.java:100) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.recommendation.scheduling.TaskConsumer.run(TaskConsumer.java:63) [classes/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by reckart** [comment]
Seems to happen in the NamedEntityLinker. Apparently it sometimes returns "null" sentences from `predictSentences(tokens)` as in `mergeAdjacentTokensWithSameLabel`, the `sentences` parameter ends up being something like this `[[], [], [], [], [], [], [], [], [], [], null, [], [], [], ...`.
