### ISSUE TITLE
Use extension point instead of reflections  for CasDoctor

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#3090]
**Describe the refactoring action**
Use extension point instead of reflections  for CasDoctor.

**Expected benefit**
Remove dependency on reflections library.

**Comment by reckart** [comment]
Exception found:

```
Jun 14 09:56:51 blinky inception-experimental.jar[26240]: 2022-06-14 09:56:51 ERROR [rec] CasDoctor - Cannot perform repair []
Jun 14 09:56:51 blinky inception-experimental.jar[26240]: java.util.NoSuchElementException: Unknown repair []
Jun 14 09:56:51 blinky inception-experimental.jar[26240]:         at de.tudarmstadt.ukp.clarin.webanno.diag.CasDoctor.lambda$repair$1(CasDoctor.java:120) ~[inception-diag-24.0-SNAPSHOT.jar!/:?]
Jun 14 09:56:51 blinky inception-experimental.jar[26240]:         at java.util.Optional.orElseThrow(Optional.java:408) ~[?:?]
Jun 14 09:56:51 blinky inception-experimental.jar[26240]:         at de.tudarmstadt.ukp.clarin.webanno.diag.CasDoctor.repair(CasDoctor.java:119) ~[inception-diag-24.0-SNAPSHOT.jar!/:?]
Jun 14 09:56:51 blinky inception-experimental.jar[26240]:         at de.tudarmstadt.ukp.clarin.webanno.diag.CasDoctor.repair(CasDoctor.java:102) ~[inception-diag-24.0-SNAPSHOT.jar!/:?]
Jun 14 09:56:51 blinky inception-experimental.jar[26240]:         at de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.CasStorageServiceImpl.analyzeAndRepair(CasStorageServiceImpl.java:643) ~[inception-api-dao-24.0-SNAPSHOT.jar!/:?]
Jun 14 09:56:51 blinky inception-experimental.jar[26240]:         at de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.CasStorageServiceImpl.analyzeAndRepair(CasStorageServiceImpl.java:609) ~[inception-api-dao-24.0-SNAPSHOT.jar!/:?]
Jun 14 09:56:51 blinky inception-experimental.jar[26240]:         at de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.CasStorageServiceImpl.repairAndUpgradeCasIfRequired(CasStorageServiceImpl.java:487) ~[inception-api-dao-24.0-SNAPSHOT.jar!/:?]
Jun 14 09:56:51 blinky inception-experimental.jar[26240]:         at de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.CasStorageServiceImpl.readOrCreateUnmanagedCas(CasStorageServiceImpl.java:537) ~[inception-api-dao-24.0-SNAPSHOT.jar!/:?]
Jun 14 09:56:51 blinky inception-experimental.jar[26240]:         at de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.CasStorageServiceImpl.readOrCreateCas(CasStorageServiceImpl.java:335) ~[inception-api-dao-24.0-SNAPSHOT.jar!/:?]
Jun 14 09:56:51 blinky inception-experimental.jar[26240]:         at de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.CasStorageServiceImpl$$FastClassBySpringCGLIB$$70b0ffa.invoke(<generated>) ~[inception-api-dao-24.0-SNAPSHOT.jar!/:?]
```
