### ISSUE TITLE
Cannot connect to ElasticSearch repository

### ISSUE THREAD

**Issue by ChanatipSaetia** [inception-project/inception#3349]
**Describe the bug**
I followed "Setting up a simple ElasticSearch document repository" session with the same settings. I found that at step 15, it still shows "No Records Found". In the logging output of inception, I found an error.

**To Reproduce**
Follow "Setting up a simple ElasticSearch document repository" session.

**Expected behavior**
Be able to found the document.

**Screenshots**
![image](https://user-images.githubusercontent.com/13812347/188654524-a362c05c-a84a-4601-8334-4a48c30196b7.png)

**Please complete the following information:**
 - Version and build ID: 24.1
 - OS: Ubuntu 20.2
 - Browser: chrome

**Comment by reckart** [comment]
I also get an error, but it is a different one:

```
2022-09-06 21:07:20 ERROR [SYSTEM] [dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Filter execution threw an exception] with root cause
java.lang.NoSuchFieldError: LUCENE_6_0_0
	at org.elasticsearch.Version.<clinit>(Version.java:51) ~[elasticsearch-6.8.23.jar!/:6.8.23]
	at org.elasticsearch.common.logging.DeprecationLogger.<clinit>(DeprecationLogger.java:144) ~[elasticsearch-6.8.23.jar!/:6.8.23]
	at org.elasticsearch.search.builder.SearchSourceBuilder.<clinit>(SearchSourceBuilder.java:81) ~[elasticsearch-6.8.23.jar!/:6.8.23]
	at de.tudarmstadt.ukp.inception.externalsearch.elastic.ElasticSearchProvider.executeQuery(ElasticSearchProvider.java:84) ~[inception-external-search-elastic-24.3-SNAPSHOT.jar!/:?]
	at de.tudarmstadt.ukp.inception.externalsearch.elastic.ElasticSearchProvider.executeQuery(ElasticSearchProvider.java:58) ~[inception-external-search-elastic-24.3-SNAPSHOT.jar!/:?]
	at de.tudarmstadt.ukp.inception.externalsearch.ExternalSearchServiceImpl.query(ExternalSearchServiceImpl.java:85) ~[inception-external-search-core-24.3-SNAPSHOT.jar!/:?]
...
```

**Comment by reckart** [comment]
Looks like we forgot to upgrade the ElasticSearch version in the v24.0 release. v24.3 will have the proper version and ElasticSearch support will work again then.

**Comment by reckart** [comment]
Actually, I'm afraid we cannot ship ElasticSearch support anymore. ElasticSearch have changed their license with version 7.11.0 and it is no longer under an open source licensed approved by the OSI. The last ElasticSearch version that is under the Apache License is 7.10.0. but unfortunately it has security problems.

 In the `24.x` branch, ElasticSearch support will remain in the repository, but it will no longer be included in the default built.

As a replacement, OpenSearch support will be added in v25.0.v - https://github.com/inception-project/inception/issues/3356
