### ISSUE TITLE
Index error importing documents into a new project

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#335]
```
2018-06-25 17:14:41 INFO [admin] MtasDocumentIndex - Opening index for project A new horizon
2018-06-25 17:14:41 ERROR [SYSTEM] MtasDocumentIndex - Unable to open index
org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /Users/bluefire/UKP/Library/inception/repository/project/67/indexMtas/write.lock
	at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:139) ~[lucene-core-7.1.0.jar:7.1.0 84c90ad2c0218156c840e19a64d72b8a38550659 - ubuntu - 2017-10-13 16:12:42]
	at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41) ~[lucene-core-7.1.0.jar:7.1.0 84c90ad2c0218156c840e19a64d72b8a38550659 - ubuntu - 2017-10-13 16:12:42]
	at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45) ~[lucene-core-7.1.0.jar:7.1.0 84c90ad2c0218156c840e19a64d72b8a38550659 - ubuntu - 2017-10-13 16:12:42]
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:947) ~[lucene-core-7.1.0.jar:7.1.0 84c90ad2c0218156c840e19a64d72b8a38550659 - ubuntu - 2017-10-13 16:12:42]
	at de.tudarmstadt.ukp.inception.search.index.mtas.MtasDocumentIndex.openLuceneIndex(MtasDocumentIndex.java:667) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.search.index.mtas.MtasDocumentIndex.openPhysicalIndex(MtasDocumentIndex.java:600) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.search.index.mtas.MtasDocumentIndex.createPhysicalIndex(MtasDocumentIndex.java:624) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.search.SearchServiceImpl.reindex(SearchServiceImpl.java:326) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.search.SearchServiceImpl$$FastClassBySpringCGLIB$$d6146f50.invoke(<generated>) ~[classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747) ~[spring-aop-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) [spring-tx-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) [spring-tx-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) [spring-aop-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at de.tudarmstadt.ukp.inception.search.SearchServiceImpl$$EnhancerBySpringCGLIB$$a70fc823.reindex(<generated>) [classes/:?]
	at de.tudarmstadt.ukp.inception.search.scheduling.tasks.ReindexTask.run(ReindexTask.java:46) [classes/:?]
	at de.tudarmstadt.ukp.inception.search.scheduling.TaskConsumer.run(TaskConsumer.java:63) [classes/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

0.4.0-SNAPSHOT (2018-06-25 16:42:11, build e90cb986a7587b18f095140cdfdce267d1e1bbd1)

**Comment by reckart** [comment]
Not observed again.
