### ISSUE TITLE
Create Instance throws Null Pointer Exception

### ISSUE THREAD

**Issue by naveen2507** [inception-project/inception#353]
**Describe the bug**
Create instance in KB UI throws NPE for `Objects.requireNonNull(language);` in SimpleLiteral.java

```2018-06-29 15:15:55 ERROR [admin] KnowledgeBasePage - Error: null
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_161]
	at org.eclipse.rdf4j.model.impl.SimpleLiteral.setLanguage(SimpleLiteral.java:121) ~[rdf4j-model-2.2.4.jar:?]
	at org.eclipse.rdf4j.model.impl.SimpleLiteral.<init>(SimpleLiteral.java:85) ~[rdf4j-model-2.2.4.jar:?]
	at org.eclipse.rdf4j.sail.nativerdf.model.NativeLiteral.<init>(NativeLiteral.java:53) ~[rdf4j-sail-nativerdf-2.2.4.jar:?]
	at org.eclipse.rdf4j.sail.nativerdf.model.NativeLiteral.<init>(NativeLiteral.java:49) ~[rdf4j-sail-nativerdf-2.2.4.jar:?]
	at org.eclipse.rdf4j.sail.nativerdf.ValueStore.createLiteral(ValueStore.java:720) ~[rdf4j-sail-nativerdf-2.2.4.jar:?]
	at org.eclipse.rdf4j.sail.nativerdf.ValueStore.createLiteral(ValueStore.java:42) ~[rdf4j-sail-nativerdf-2.2.4.jar:?]
	at de.tudarmstadt.ukp.inception.kb.graph.KBInstance.write(KBInstance.java:135) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl.lambda$6(KnowledgeBaseServiceImpl.java:443) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl.update(KnowledgeBaseServiceImpl.java:597) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl.createInstance(KnowledgeBaseServiceImpl.java:440) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl$$FastClassBySpringCGLIB$$77259834.invoke(<generated>) ~[classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685) ~[spring-aop-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl$$EnhancerBySpringCGLIB$$2c620198.createInstance(<generated>) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:508) ~[wicket-ioc-7.10.0.jar:7.10.0]
	at com.sun.proxy.$Proxy176.createInstance(Unknown Source) ~[?:?]
	at de.tudarmstadt.ukp.inception.ui.kb.InstanceInfoPanel.actionCreate(InstanceInfoPanel.java:59) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.support.lambda.LambdaAjaxButton.onSubmit(LambdaAjaxButton.java:52) [webanno-support-3.5.0-SNAPSHOT.jar:?]
	at org.apache.wicket.ajax.markup.html.form.AjaxButton$1.onSubmit(AjaxButton.java:113) [wicket-core-7.10.0.jar:7.10.0]
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior$AjaxFormSubmitter.onSubmit(AjaxFormSubmitBehavior.java:218) [wicket-core-7.10.0.jar:7.10.0]
	at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1311) [wicket-core-7.10.0.jar:7.10.0]
	at org.apache.wicket.markup.html.form.Form.process(Form.java:977) [wicket-core-7.10.0.jar:7.10.0]
```

**To Reproduce**
1. Go to KB UI
2. Click on Create Instance and enter the value 
4. See error 'null'

**Expected behavior**
Create Instance 

**Please complete the following information:**
 - Technische Universität Darmstadt -- Computer Science Department -- INCEpTION 𝜶 -- 0.4.0-SNAPSHOT (2018-06-29 15:00:58, build b6513fc5366c1ca8da351c754d72fc2582eac41e)
 -  Linux
 - chrome

**Comment by naveen2507** [comment]
Issue after the commit from #160 in KBInstance.java : ` vf.createLiteral(name)` to `vf.createLiteral(name, language)`
