### ISSUE TITLE
Inception with ExternalRecommender: Timeout Error

### ISSUE THREAD

**Issue by pvn25** [inception-project/inception#3642]
**Describe the bug**

I have inception and an external recommender servers running on one machine. External recommender is started as an #[aridne server](https://github.com/inception-project/inception-external-recommender). I load a CSV file with just 10k sentences for annotation in inception. And as soon as I annotate a sentence, I get “Error while sending request: request timed out” messages inside the inception tool. so Inception is not able to send any data to the recommender server. The file size itself is just 2MBs and I can confirm that there is no error with external recommender. I did set the following two lines in settings.properties file at `~/.inception/` location:
 
```
  recommender.external.connect-timeout=18000s
  recommender.external.read-timeout=18000s
```

**Screenshots**
![inception-timeout-error](https://user-images.githubusercontent.com/6302707/207989892-1b97857b-2503-41b9-bbbb-17781973eb33.jpg)

**Please complete the following information:**
- Version: Inception 25.2
- OS: Red Hat Enterprise Linux 8.6
- Browser: chrome

**Comment by reckart** [comment]
What are you using to run ariadne? Flask or Unicron? How many workers have you set up?

**Comment by reckart** [comment]
Can you provide an excerpt of the INCEpTION server log so we can see where exactly the timeout exception is triggered?

**Comment by pvn25** [comment]
I am using ariadne with Flask. I have not tried unicorn with multiple workers. Here's the server log that I get:

```
ERROR [SYSTEM] RecommendationServiceImpl - Error applying recommender [[RecName] Remote classifier](0) for user [admin] to document [valid.csv](12) in project [ProjectName](0) - skipping recommender
de.tudarmstadt.ukp.inception.recommendation.api.recommender.RecommendationException: Error while sending request: request timed out
	at de.tudarmstadt.ukp.inception.recommendation.imls.external.v1.ExternalRecommender.sendRequest(ExternalRecommender.java:284) ~[inception-imls-external-25.2.jar!/:?]
	at de.tudarmstadt.ukp.inception.recommendation.imls.external.v1.ExternalRecommender.predict(ExternalRecommender.java:178) ~[inception-imls-external-25.2.jar!/:?]
	at de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl.generateSuggestions(RecommendationServiceImpl.java:1604) ~[inception-recommendation-25.2.jar!/:?]
	at de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl.computePredictions(RecommendationServiceImpl.java:1396) ~[inception-recommendation-25.2.jar!/:?]
	at de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl.computePredictions(RecommendationServiceImpl.java:1456) ~[inception-recommendation-25.2.jar!/:?]
	at de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl.computePredictions(RecommendationServiceImpl.java:1520) ~[inception-recommendation-25.2.jar!/:?]
	at de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl$$FastClassBySpringCGLIB$$7b2c1577.invoke(<generated>) ~[inception-recommendation-25.2.jar!/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.23.jar!/:5.3.23]
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386) ~[spring-aop-5.3.23.jar!/:5.3.23]
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85) ~[spring-aop-5.3.23.jar!/:5.3.23]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704) ~[spring-aop-5.3.23.jar!/:5.3.23]
	at de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl$$EnhancerBySpringCGLIB$$1cdda75d.computePredictions(<generated>) ~[inception-recommendation-25.2.jar!/:?]
	at de.tudarmstadt.ukp.inception.recommendation.tasks.PredictionTask.execute(PredictionTask.java:97) ~[inception-recommendation-25.2.jar!/:?]
	at de.tudarmstadt.ukp.inception.scheduling.Task.run(Task.java:109) ~[inception-scheduling-25.2.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.net.http.HttpTimeoutException: request timed out
	at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:559) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119) ~[java.net.http:?]
	at de.tudarmstadt.ukp.inception.recommendation.imls.external.v1.ExternalRecommender.sendRequest(ExternalRecommender.java:281) ~[inception-imls-external-25.2.jar!/:?]
	... 16 more
```

**Comment by reckart** [comment]
Can you please try unicorn as documented here: https://github.com/inception-project/inception-external-recommender#development

**Comment by reckart** [comment]
Btw. if you are running e.g. in a cloud environment, you'd also need to make sure that the network infrastructure around INCEpTION and the external recommender is also configured to allow long-running requests, otherwise it the network layer might even terminate the request.

**Comment by reckart** [comment]
Closing as there was no further feedback. If the problem persists with unicorn, please comment.
