### ISSUE TITLE
Rare error in shared document pool

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#3821]
**Describe the bug**
Regular unit testing reported a failure in `de.tudarmstadt.ukp.inception.documents.DocumentServiceImplConcurrencyTest.testHighConcurrencyMultiUser`

**To Reproduce**
Unclear - the issue does seem to happen only very very rarely. 

**Expected behavior**
No failure.

**Screenshots**
```
Exception in thread "RO0" java.lang.RuntimeException: de.tudarmstadt.ukp.clarin.webanno.api.casstorage.CasSessionException: Unable to borrow CAS
	at de.tudarmstadt.ukp.inception.documents.DocumentServiceImplConcurrencyTest$SharedReadOnlyTask.run(DocumentServiceImplConcurrencyTest.java:368)
Caused by: de.tudarmstadt.ukp.clarin.webanno.api.casstorage.CasSessionException: Unable to borrow CAS
	at de.tudarmstadt.ukp.inception.annotation.storage.CasStorageServiceImpl.borrowCas(CasStorageServiceImpl.java:488)
	at de.tudarmstadt.ukp.inception.annotation.storage.CasStorageServiceImpl$WithExclusiveAccess.<init>(CasStorageServiceImpl.java:872)
	at de.tudarmstadt.ukp.inception.annotation.storage.CasStorageServiceImpl.readOrCreateCas(CasStorageServiceImpl.java:404)
	at de.tudarmstadt.ukp.inception.documents.DocumentServiceImpl.readAnnotationCas(DocumentServiceImpl.java:920)
	at de.tudarmstadt.ukp.inception.documents.DocumentServiceImplConcurrencyTest$SharedReadOnlyTask.run(DocumentServiceImplConcurrencyTest.java:362)
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.commons.pool2.impl.GenericKeyedObjectPool$ObjectDeque.getNumInterested()" because "objectDeque" is null
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.deregister(GenericKeyedObjectPool.java:821)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:507)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:350)
	at de.tudarmstadt.ukp.inception.annotation.storage.CasStorageServiceImpl.borrowCas(CasStorageServiceImpl.java:463)
	at de.tudarmstadt.ukp.inception.annotation.storage.CasStorageServiceImpl$WithExclusiveAccess.<init>(CasStorageServiceImpl.java:872)
	at de.tudarmstadt.ukp.inception.annotation.storage.CasStorageServiceImpl.readOrCreateCas(CasStorageServiceImpl.java:404)
	at de.tudarmstadt.ukp.inception.documents.DocumentServiceImpl.readAnnotationCas(DocumentServiceImpl.java:920)
	at de.tudarmstadt.ukp.inception.documents.DocumentServiceImpl$MockitoMock$GBXIxot6.readAnnotationCas$accessor$3VHGoTtt(Unknown Source)
	at de.tudarmstadt.ukp.inception.documents.DocumentServiceImpl$MockitoMock$GBXIxot6$auxiliary$izEJhDIP.call(Unknown Source)
	at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
	at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
	at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:142)
	at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:45)
	at org.mockito.Answers.answer(Answers.java:90)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:111)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:56)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:145)
	at de.tudarmstadt.ukp.inception.documents.DocumentServiceImpl$MockitoMock$GBXIxot6.readAnnotationCas(Unknown Source)
	... 1 more
```

**Please complete the following information:**
 - Version and build ID: 27.0-SNAPSHOT (ff57468c4cad32e31427f21c39d6bc12e59c6435)

**Additional context**

Parallel Maven build with 4 parallel build threads was used (`-T4`) - but the same parameter has been used since a long time and these failures were never observed.

**Related issues**
* I have opened an issue for this in the Apache Commons Pool tracker - it seems it might be a bug in the pool implementation: https://issues.apache.org/jira/browse/POOL-411

**Comment by reckart** [comment]
Upstream has implemented a fix, but there is no release containing the fix yet.
