### ISSUE TITLE
Unable to index non-string primitive features

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#391]
**Describe the bug**
None-string fields do not get indexed.

```
2018-07-06 18:39:03 ERROR [simon.eichler] MtasUimaParser - Unable to index document
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at de.tudarmstadt.ukp.inception.search.index.mtas.MtasUimaParser.indexFeatureValue(MtasUimaParser.java:247) ~[inception-search-mtas-0.4.0.jar!/:?]
        at de.tudarmstadt.ukp.inception.search.index.mtas.MtasUimaParser.createTokenCollection(MtasUimaParser.java:220) ~[inception-search-mtas-0.4.0.jar!/:?]
        at mtas.analysis.MtasTokenizer.constructTokenCollection(MtasTokenizer.java:238) ~[mtas-7.1.0.2.jar!/:?]
        at mtas.analysis.MtasTokenizer.reset(MtasTokenizer.java:171) ~[mtas-7.1.0.2.jar!/:?]
```

**To Reproduce**
1. Create a layer with a boolean feature
2. Create an annotation from that layer

**Expected behavior**

**Screenshots**
Non-string values should be indexed properly, e.g. boolean values should be indexed as "true" or "false".

**Please complete the following information:**
 - Version and build ID: INCEpTION 𝜶 -- 0.4.0 (2018-07-06 17:11:43, build aca896f929f83bd8e6aff7339398315b1db67568)

**Comment by naveen2507** [comment]
@reckart exception from `return (T) (Boolean) aFS.getBooleanValue(feature);` in function `WebAnnoCasUtil.getFeature(FeatureStructure aFS, String aFeatureName)`
