### ISSUE TITLE
Projects may not delete if WebSocket-based event notification is enabled

### ISSUE THREAD

**Issue by martin-lentschat** [inception-project/inception#3926]
This bug appeared after I migrated from Inception 23.11 to version 27.3 (might not be related).

When trying to delete a project, I get an error message and the project won't be deleted. This happens with old projects, or with new empty ones. The error message also change between the first time one try to delete it and the next times.

*First click*
![image](https://user-images.githubusercontent.com/26545993/230123345-acdaf050-0a70-48b2-bd1e-ec2815db69aa.png)

*Second click*
![image](https://user-images.githubusercontent.com/26545993/230123517-41d6bcf4-4974-438a-a6e2-8b0778a98228.png)

You will find the related logs attached:
[application.log](https://github.com/inception-project/inception/files/11160335/application.log)

**Comment by reckart** [comment]
So I see it directly... 

```
2023-04-05 17:07:24 ERROR [SYSTEM] ProjectSettingsPage - Error: Project [11] is being deleted, index no longer accessible.
java.lang.IllegalStateException: Project [11] is being deleted, index no longer accessible.
	at de.tudarmstadt.ukp.inception.search.SearchServiceImpl.acquireIndex(SearchServiceImpl.java:324) ~[inception-search-core-27.3.jar!/:?]
	at de.tudarmstadt.ukp.inception.search.SearchServiceImpl.beforeProjectRemove(SearchServiceImpl.java:290) ~[inception-search-core-27.3.jar!/:?]
	at de.tudarmstadt.ukp.inception.search.SearchServiceImpl$$FastClassBySpringCGLIB$$d6146f50.invoke(<generated>) ~[inception-search-core-27.3.jar!/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.25.jar!/:5.3.25]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.25.jar!/:5.3.25]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.25.jar!/:5.3.25]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.25.jar!/:5.3.25]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.25.jar!/:5.3.25]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.25.jar!/:5.3.25]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.25.jar!/:5.3.25]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.25.jar!/:5.3.25]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.25.jar!/:5.3.25]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.25.jar!/:5.3.25]
	at de.tudarmstadt.ukp.inception.search.SearchServiceImpl$$EnhancerBySpringCGLIB$$a8e95a84.beforeProjectRemove(<generated>) ~[inception-search-core-27.3.jar!/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor282.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344) ~[spring-context-5.3.25.jar!/:5.3.25]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229) ~[spring-context-5.3.25.jar!/:5.3.25]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166) ~[spring-context-5.3.25.jar!/:5.3.25]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.25.jar!/:5.3.25]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.25.jar!/:5.3.25]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.25.jar!/:5.3.25]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.25.jar!/:5.3.25]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.25.jar!/:5.3.25]
	at de.tudarmstadt.ukp.clarin.webanno.project.ProjectServiceImpl.removeProject(ProjectServiceImpl.java:633) ~[inception-project-27.3.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.project.ProjectServiceImpl$$FastClassBySpringCGLIB$$87162b14.invoke(<generated>) ~[inception-project-27.3.jar!/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.25.jar!/:5.3.25]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.25.jar!/:5.3.25]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.25.jar!/:5.3.25]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.25.jar!/:5.3.25]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.25.jar!/:5.3.25]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.25.jar!/:5.3.25]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.25.jar!/:5.3.25]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.25.jar!/:5.3.25]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.25.jar!/:5.3.25]
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:67) ~[spring-security-core-5.8.1.jar!/:5.8.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.25.jar!/:5.3.25]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.25.jar!/:5.3.25]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.25.jar!/:5.3.25]
	at de.tudarmstadt.ukp.clarin.webanno.project.ProjectServiceImpl$$EnhancerBySpringCGLIB$$d35ab9c6.removeProject(<generated>) ~[inception-project-27.3.jar!/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor279.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.wicket.proxy.jdk.JdkProxyFactory$JdkHandler.invoke(JdkProxyFactory.java:172) ~[wicket-ioc-9.12.0.jar!/:9.12.0]
	at com.sun.proxy.$Proxy274.removeProject(Unknown Source) ~[?:?]
	at de.tudarmstadt.ukp.inception.ui.project.dangerzone.ProjectDangerZonePanel.actionDeletePerform(ProjectDangerZonePanel.java:91) ~[inception-ui-project-27.3.jar!/:?]
```

**Comment by reckart** [comment]
Ok, so my guess here might be that it is a very large project or you have a slow system and that you tried to delete the project and before it was done deleting, you tried deleting it again - that's what the stack trace tries to tell me - which is probably not what happened, rightß

**Comment by reckart** [comment]
Ah, there was a previous error :) I missed that one... let's see...

**Comment by reckart** [comment]
Ok, so on the first click, the project got deleted, but when the system was wrapping up the deletion, an error happend. You should find that the project is no longer there if you go to the project overview page - well, it might still be there if the DB transaction has been cancelled, but it will be in a zombie state as e.g. all data from it will be gone.

The second click produces an error because the error because of the zombie state.

**Comment by reckart** [comment]
It seems you have `websocket.logged-events.enabled` in your settings.properties. You should disable it.

**Comment by martin-lentschat** [comment]
Yes, it works! Thanks (and sorry for bothering you with these kinds of questions, I'm able to follow instructions and understand some basics about servers but I'm still struggling with debugging).

**Comment by reckart** [comment]
No worries - I fixed/improved several things based on your feedback!

**Comment by reckart** [comment]
If you upgrade to the version 27.4 release yesterday, should hopefully find that this here is no longer a problem.
