### ISSUE TITLE
Cannot create subclass

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#421]
**Describe the bug**
An exception when trying to create a subclass in the knowledge base page:

```
2018-07-26 12:05:20 ERROR [admin] KnowledgeBasePanel - Unable to find property subclassof.
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_144]
	at de.tudarmstadt.ukp.inception.ui.kb.SubclassCreationDialog$ContentPanel.actionCreateSubclass(SubclassCreationDialog.java:132) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.support.lambda.LambdaAjaxButton.onSubmit(LambdaAjaxButton.java:52) [classes/:?]
	at org.apache.wicket.ajax.markup.html.form.AjaxButton$1.onSubmit(AjaxButton.java:113) [wicket-core-7.10.0.jar:7.10.0]
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior$AjaxFormSubmitter.onSubmit(AjaxFormSubmitBehavior.java:218) [wicket-core-7.10.0.jar:7.10.0]
	at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1311) [wicket-core-7.10.0.jar:7.10.0]
	at org.apache.wicket.markup.html.form.Form.process(Form.java:977) [wicket-core-7.10.0.jar:7.10.0]
	at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:798) [wicket-core-7.10.0.jar:7.10.0]
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior.onEvent(AjaxFormSubmitBehavior.java:174) [wicket-core-7.10.0.jar:7.10.0] 
   ...
```

**To Reproduce**
1. Create a new empty local KB in the project settings (I used the "OWL" profile)
2. Open the KB in the KB page
3. Create a new top-level class `AAA`
4. Press "create subclass" and try creating a class `BBB`

**Expected behavior**
`BBB` is created as a subclass of `AAA`

**Please complete the following information:**
 - Version and build ID: INCEpTION 𝜶 -- 0.5.0-SNAPSHOT (2018-07-26 11:27:24, build 98aaa3c967e31eed6a4270b8139698e7af67e399)

**Additional context**

**Comment by naveen2507** [comment]
@reckart Issue because of no property found for subClassOf in ontology.

**Comment by reckart** [comment]
Thanks for fixing it. Now I could finally test #51
