### ISSUE TITLE
Cannot add statement

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#422]
**Describe the bug**
Unable to add a new statement to an instance.

```
Caused by: java.lang.NullPointerException: iriString must not be null
	at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_144]
	at org.eclipse.rdf4j.model.impl.SimpleIRI.setIRIString(SimpleIRI.java:73) ~[rdf4j-model-2.2.4.jar:?]
	at org.eclipse.rdf4j.model.impl.SimpleIRI.<init>(SimpleIRI.java:65) ~[rdf4j-model-2.2.4.jar:?]
	at org.eclipse.rdf4j.sail.nativerdf.model.NativeIRI.<init>(NativeIRI.java:39) ~[rdf4j-sail-nativerdf-2.2.4.jar:?]
	at org.eclipse.rdf4j.sail.nativerdf.model.NativeIRI.<init>(NativeIRI.java:35) ~[rdf4j-sail-nativerdf-2.2.4.jar:?]
	at org.eclipse.rdf4j.sail.nativerdf.ValueStore.createIRI(ValueStore.java:700) ~[rdf4j-sail-nativerdf-2.2.4.jar:?]
	at org.eclipse.rdf4j.sail.nativerdf.ValueStore.createIRI(ValueStore.java:42) ~[rdf4j-sail-nativerdf-2.2.4.jar:?]
	at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl.readKBIdentifier(KnowledgeBaseServiceImpl.java:1024) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl$$FastClassBySpringCGLIB$$77259834.invoke(<generated>) ~[classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl$$EnhancerBySpringCGLIB$$d74becb0.readKBIdentifier(<generated>) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:508) ~[wicket-ioc-7.10.0.jar:7.10.0]
	at com.sun.proxy.$Proxy192.readKBIdentifier(Unknown Source) ~[?:?]
	at de.tudarmstadt.ukp.inception.ui.kb.stmt.editor.StatementEditor$EditMode.<init>(StatementEditor.java:320) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.ui.kb.stmt.editor.StatementEditor.<init>(StatementEditor.java:98) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.ui.kb.stmt.StatementGroupPanel$ExistingStatementGroupFragment$1.populateItem(StatementGroupPanel.java:252) ~[classes/:?]
	at org.apache.wicket.markup.repeater.RefreshingView$1.newItem(RefreshingView.java:114) ~[wicket-core-7.10.0.jar:7.10.0]
	at org.apache.wicket.markup.repeater.ReuseIfModelsEqualStrategy$1.next(ReuseIfModelsEqualStrategy.java:88) ~[wicket-core-7.10.0.jar:7.10.0]
	at org.apache.wicket.markup.repeater.ReuseIfModelsEqualStrategy$1.next(ReuseIfModelsEqualStrategy.java:70) ~[wicket-core-7.10.0.jar:7.10.0]
	at org.apache.wicket.markup.repeater.RefreshingView.addItems(RefreshingView.java:189) ~[wicket-core-7.10.0.jar:7.10.0]
	at org.apache.wicket.markup.repeater.RefreshingView.onPopulate(RefreshingView.java:97) ~[wicket-core-7.10.0.jar:7.10.0]
	at org.apache.wicket.markup.repeater.AbstractRepeater.onBeforeRender(AbstractRepeater.java:124) ~[wicket-core-7.10.0.jar:7.10.0]
	at org.apache.wicket.Component.internalBeforeRender(Component.java:950) ~[wicket-core-7.10.0.jar:7.10.0]
	at org.apache.wicket.Component.beforeRender(Component.java:1018) ~[wicket-core-7.10.0.jar:7.10.0]
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1825) ~[wicket-core-7.10.0.jar:7.10.0]
	... 169 more
```

**To Reproduce**
1. Create a new empty local KB in the project settings (I used the "OWL" profile)
2. Open the KB in the KB page
3. Create a new top-level class `AAA`
4. Press "create instance" and creating an instance `An AAA`
5. Create a new property called "comment"
6. Go back to the "An AAA" instance, select "comment" from the dropdown and click the checkmark to create the new statement

**Expected behavior**
A statement editor for the comment property should come up so I can edit the statement.

**Please complete the following information:**
 - Version and build ID: INCEpTION 𝜶 -- 0.5.0-SNAPSHOT (2018-07-26 11:27:24, build 98aaa3c967e31eed6a4270b8139698e7af67e399)

**Comment by naveen2507** [comment]
Issue fixed in #51
