### ISSUE TITLE
Cannot export project with "WebAnno TSV3" format

### ISSUE THREAD

**Issue by Rentier** [inception-project/inception#432]
**Describe the bug**

When exporting a project with format "WebAnno TSV3", it looks like the export is created, but it gets stuck at 100%.

The error message is:

```
2018-08-02 09:21:47 ERROR [klie] ProjectPage - Unexpected error during project export
java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.compare(Ljava/lang/String;Ljava/lang/String;)I
	at de.tudarmstadt.ukp.clarin.webanno.tsv.internal.tsv3x.model.TsvSchema.lambda$getColumns$1(TsvSchema.java:74) ~[webanno-io-tsv-3.5.0-beta-2.jar!/:?]
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:1.8.0_131]
	at java.util.TimSort.sort(TimSort.java:220) ~[?:1.8.0_131]
	at java.util.Arrays.sort(Arrays.java:1512) ~[?:1.8.0_131]
	at java.util.ArrayList.sort(ArrayList.java:1454) ~[?:1.8.0_131]
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:387) ~[?:1.8.0_131]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:1.8.0_131]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_131]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_131]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_131]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_131]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_131]
	at de.tudarmstadt.ukp.clarin.webanno.tsv.internal.tsv3x.model.TsvSchema.getColumns(TsvSchema.java:77) ~[webanno-io-tsv-3.5.0-beta-2.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.tsv.internal.tsv3x.model.TsvSchema.getHeaderColumns(TsvSchema.java:105) ~[webanno-io-tsv-3.5.0-beta-2.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.tsv.internal.tsv3x.Tsv3XSerializer.write(Tsv3XSerializer.java:88) ~[webanno-io-tsv-3.5.0-beta-2.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.tsv.internal.tsv3x.Tsv3XSerializer.write(Tsv3XSerializer.java:71) ~[webanno-io-tsv-3.5.0-beta-2.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoTsv3XWriter.process(WebannoTsv3XWriter.java:60) ~[webanno-io-tsv-3.5.0-beta-2.jar!/:?]
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:401) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:318) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:271) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:262) ~[uimafit-core-2.4.0.jar!/:2.4.0]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl.exportCasToFile(ImportExportServiceImpl.java:557) ~[webanno-api-dao-3.5.0-beta-2.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl.exportAnnotationDocument(ImportExportServiceImpl.java:158) ~[webanno-api-dao-3.5.0-beta-2.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl.exportAnnotationDocument(ImportExportServiceImpl.java:120) ~[webanno-api-dao-3.5.0-beta-2.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl$$FastClassBySpringCGLIB$$256f1e29.invoke(<generated>) ~[webanno-api-dao-3.5.0-beta-2.jar!/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.ImportExportServiceImpl$$EnhancerBySpringCGLIB$$63f11c76.exportAnnotationDocument(<generated>) ~[webanno-api-dao-3.5.0-beta-2.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.exporters.CuratedDocumentsExporter.exportData(CuratedDocumentsExporter.java:123) ~[webanno-api-dao-3.5.0-beta-2.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl.exportProject(ProjectExportServiceImpl.java:186) ~[webanno-api-dao-3.5.0-beta-2.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl.exportProject(ProjectExportServiceImpl.java:128) ~[webanno-api-dao-3.5.0-beta-2.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl$$FastClassBySpringCGLIB$$3d43e16f.invoke(<generated>) ~[webanno-api-dao-3.5.0-beta-2.jar!/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl$$EnhancerBySpringCGLIB$$588a208.exportProject(<generated>) ~[webanno-api-dao-3.5.0-beta-2.jar!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:508) ~[wicket-ioc-7.10.0.jar!/:7.10.0]
	at com.sun.proxy.$Proxy205.exportProject(Unknown Source) ~[?:?]
	at de.tudarmstadt.ukp.clarin.webanno.ui.project.export.ProjectExportPanel$FileGenerator.run(ProjectExportPanel.java:372) [webanno-ui-project-3.5.0-beta-2.jar!/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
2018-08-02 09:21:48 INFO [klie] ApplicationPageBase - klie: Project export cancelled

```

**To Reproduce**
1. Go to 'blinky stable'
2. Select `ClS: medical entities`
3. Export with format "WebAnno TSV3"

**Expected behavior**
The project is exported and downloaded.

**Please complete the following information:**
- Technische Universität Darmstadt -- Computer Science Department -- INCEpTION 𝜶 -- 0.4.1 (2018-07-20 12:36:20, build de3629c5c054990f5da64b014a719cf2e42e148a)
-Version 68.0.3440.75 (Official Build) (64-bit)
- blinky stable

**Additional context**

I can reproduce it when I export the project from blinky as plain text, import it in my local installation and the export it again as   "WebAnno TSV3".

**Comment by reckart** [comment]
The missing method was introduced in Commons Lang 3 3.5 but the INCEpTION top-level POM forces the version of this dependency to 3.4. The latest version (which should be used) is 3.7.

Update the dependency - that should fix the problem.
