### ISSUE TITLE
Error importing layers: NoSuchElementException: No value present

### ISSUE THREAD

**Issue by tpluscode** [inception-project/inception#4986]
**Describe the bug**

I used one project to test-drive a set of layers with the intent to import them again in another.

I expect that the problem is with layers which reference Knowledge Bases. KBs cannot be exported so what can I do?

**To Reproduce**
Steps to reproduce the behavior, presumably:
1. Create a KB
2. Create a layer which has a KB property
3. Export all layers (UIMA XML)
4. Import in another project

**Expected behavior**

Importing should succeed

**Screenshots**

**Please complete the following information:**
 - Version and build ID: 33.1

**Comment by reckart** [comment]
Try exporting the layers as JSON instead of a UIMA Type System XML. UIMA type systems are not sufficiently expressive to capture all the options of INCEpTION. I would expect, if you export a layer with a concept feature as a UIMA XML type system and import that back again, it probably becomes a simple string feature, right?

**Comment by reckart** [comment]
Could you post the full stack trace maybe?

**Comment by reckart** [comment]
Also, I tried locally on 33.5-SNAPSHOT and can't reproduce an error. When I try it, it is as I said: the concept feature becoms a string feature on re-import.

**Comment by tpluscode** [comment]
> Could you post the full stack trace maybe?

Of course

```
2024-08-14 07:15:08 INFO [SYSTEM] AnnotationSchemaServiceImpl - Created layer [webanno.custom.BusorCoach](58) in project [wikibus brochures](4)
2024-08-14 07:15:08 INFO [SYSTEM] AnnotationSchemaServiceImpl - Created feature [BusType](74) in project [wikibus brochures](4)
2024-08-14 07:15:08 INFO [SYSTEM] AnnotationSchemaServiceImpl - Created feature [id](75) in project [wikibus brochures](4)
2024-08-14 07:15:08 INFO [SYSTEM] AnnotationSchemaServiceImpl - Created layer [webanno.custom.Engine](59) in project [wikibus brochures](4)
2024-08-14 07:15:08 INFO [SYSTEM] AnnotationSchemaServiceImpl - Created feature [Textfix](76) in project [wikibus brochures](4)
2024-08-14 07:15:08 INFO [SYSTEM] AnnotationSchemaServiceImpl - Created layer [webanno.custom.Entity](60) in project [wikibus brochures](4)
2024-08-14 07:15:08 INFO [SYSTEM] AnnotationSchemaServiceImpl - Created feature [ID](77) in project [wikibus brochures](4)
2024-08-14 07:15:08 INFO [SYSTEM] AnnotationSchemaServiceImpl - Created feature [Textfix](78) in project [wikibus brochures](4)
2024-08-14 07:15:08 INFO [SYSTEM] AnnotationSchemaServiceImpl - Created layer [webanno.custom.Gearbox](61) in project [wikibus brochures](4)
2024-08-14 07:15:08 INFO [SYSTEM] AnnotationSchemaServiceImpl - Created feature [Textfix](79) in project [wikibus brochures](4)
2024-08-14 07:15:08 ERROR [SYSTEM] ProjectLayersPanel - Error importing layers
java.util.NoSuchElementException: No value present
at java.base/java.util.Optional.get(Optional.java:143) ~[?:?]
at de.tudarmstadt.ukp.clarin.webanno.api.annotation.util.TypeSystemAnalysis.getLayer(TypeSystemAnalysis.java:80) ~[inception-api-annotation-33.1.jar!/:?]
at de.tudarmstadt.ukp.inception.schema.service.AnnotationSchemaServiceImpl.importUimaTypeSystem(AnnotationSchemaServiceImpl.java:1479) ~[inception-schema-33.1.jar!/:?]
at de.tudarmstadt.ukp.inception.schema.service.AnnotationSchemaServiceImpl$$FastClassBySpringCGLIB$$10185f48.invoke(<generated>) ~[inception-schema-33.1.jar!/:?]
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.37.jar!/:5.3.37]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792) ~[spring-aop-5.3.37.jar!/:5.3.37]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.37.jar!/:5.3.37]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762) ~[spring-aop-5.3.37.jar!/:5.3.37]
at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.37.jar!/:5.3.37]
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.37.jar!/:5.3.37]
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.37.jar!/:5.3.37]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.37.jar!/:5.3.37]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762) ~[spring-aop-5.3.37.jar!/:5.3.37]
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707) ~[spring-aop-5.3.37.jar!/:5.3.37]
at de.tudarmstadt.ukp.inception.schema.service.AnnotationSchemaServiceImpl$$EnhancerBySpringCGLIB$$224ff9c8.importUimaTypeSystem(<generated>) ~[inception-schema-33.1.jar!/:?]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at org.apache.wicket.proxy.jdk.JdkProxyFactory$JdkHandler.invoke(JdkProxyFactory.java:172) ~[wicket-ioc-9.18.0.jar!/:9.18.0]
at jdk.proxy4/jdk.proxy4.$Proxy272.importUimaTypeSystem(Unknown Source) ~[?:?]
at de.tudarmstadt.ukp.clarin.webanno.ui.project.layers.ProjectLayersPanel$ImportLayerForm.importUimaTypeSystemFile(ProjectLayersPanel.java:431) ~[inception-ui-project-33.1.jar!/:?]
at de.tudarmstadt.ukp.clarin.webanno.ui.project.layers.ProjectLayersPanel$ImportLayerForm.actionImport(ProjectLayersPanel.java:405) ~[inception-ui-project-33.1.jar!/:?]
at de.tudarmstadt.ukp.inception.support.lambda.LambdaAjaxButton.action(LambdaAjaxButton.java:86) [inception-support-33.1.jar!/:?]
at de.tudarmstadt.ukp.inception.support.lambda.LambdaAjaxButton.onSubmit(LambdaAjaxButton.java:66) [inception-support-33.1.jar!/:?]
at org.apache.wicket.ajax.markup.html.form.AjaxButton$1.onSubmit(AjaxButton.java:113) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior$AjaxFormSubmitter.onSubmit(AjaxFormSubmitBehavior.java:249) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1374) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.wicket.markup.html.form.Form.process(Form.java:1036) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:860) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior.onEvent(AjaxFormSubmitBehavior.java:202) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:154) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:630) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.wicket.core.request.handler.ListenerRequestHandler.internalInvoke(ListenerRequestHandler.java:300) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.wicket.core.request.handler.ListenerRequestHandler.invoke(ListenerRequestHandler.java:274) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.wicket.core.request.handler.ListenerRequestHandler.invokeListener(ListenerRequestHandler.java:222) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.wicket.core.request.handler.ListenerRequestHandler.respond(ListenerRequestHandler.java:202) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:910) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:63) [wicket-request-9.18.0.jar!/:9.18.0]
at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:294) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:255) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:277) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:208) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:307) [wicket-core-9.18.0.jar!/:9.18.0]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) [tomcat-embed-core-9.0.90.jar!/:?]
at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:186) [spring-orm-5.3.37.jar!/:5.3.37]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.37.jar!/:5.3.37]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) [tomcat-embed-core-9.0.90.jar!/:?]
at de.tudarmstadt.ukp.inception.support.logging.LoggingFilter.doFilter(LoggingFilter.java:58) [inception-support-33.1.jar!/:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) [tomcat-embed-core-9.0.90.jar!/:?]
at de.tudarmstadt.ukp.inception.app.config.InceptionServletContextInitializer$1.doFilterInternal(InceptionServletContextInitializer.java:96) [classes!/:?]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.37.jar!/:5.3.37]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) [tomcat-embed-core-9.0.90.jar!/:?]
at de.tudarmstadt.ukp.inception.annotation.storage.OpenCasStorageSessionForRequestFilter.doFilter(OpenCasStorageSessionForRequestFilter.java:51) [inception-annotation-storage-33.1.jar!/:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) [tomcat-embed-core-9.0.90.jar!/:?]
at io.sentry.spring.SentryUserFilter.doFilterInternal(SentryUserFilter.java:56) [sentry-spring-6.34.0.jar!/:?]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.37.jar!/:5.3.37]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) [tomcat-embed-core-9.0.90.jar!/:?]
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:352) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:164) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:151) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:129) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.37.jar!/:5.3.37]
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.37.jar!/:5.3.37]
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.37.jar!/:5.3.37]
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:225) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:190) [spring-security-web-5.8.12.jar!/:5.8.12]
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) [spring-web-5.3.37.jar!/:5.3.37]
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) [spring-web-5.3.37.jar!/:5.3.37]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) [tomcat-embed-core-9.0.90.jar!/:?]
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.3.37.jar!/:5.3.37]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.37.jar!/:5.3.37]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) [tomcat-embed-core-9.0.90.jar!/:?]
at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.37.jar!/:5.3.37]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.37.jar!/:5.3.37]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) [tomcat-embed-core-9.0.90.jar!/:?]
at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) [spring-boot-actuator-2.7.18.jar!/:2.7.18]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.37.jar!/:5.3.37]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) [tomcat-embed-core-9.0.90.jar!/:?]
at io.sentry.spring.tracing.SentryTracingFilter.doFilterWithTransaction(SentryTracingFilter.java:106) [sentry-spring-6.34.0.jar!/:?]
at io.sentry.spring.tracing.SentryTracingFilter.doFilterInternal(SentryTracingFilter.java:86) [sentry-spring-6.34.0.jar!/:?]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.37.jar!/:5.3.37]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) [tomcat-embed-core-9.0.90.jar!/:?]
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.37.jar!/:5.3.37]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.37.jar!/:5.3.37]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) [tomcat-embed-core-9.0.90.jar!/:?]
at io.sentry.spring.SentrySpringFilter.doFilterInternal(SentrySpringFilter.java:71) [sentry-spring-6.34.0.jar!/:?]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.37.jar!/:5.3.37]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:761) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.90.jar!/:?]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) [tomcat-embed-core-9.0.90.jar!/:?]
at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
2024-08-14 07:15:08 ERROR [SYSTEM] ApplicationPageBase - admin: Error importing layers: NoSuchElementException: No value present
```

**Comment by tpluscode** [comment]
I exported XML because I did not have to export each individual layer. JSON "just worked".

**Comment by tpluscode** [comment]
Here's the XML export if you'd like to try yourself
[layers-typesystem.xml.zip](https://github.com/user-attachments/files/16609049/layers-typesystem.xml.zip)

**Comment by reckart** [comment]
I think it may be related to the order in which the layers are generated from the types. It looks like the system is trying to generate a relation layer but the span layer it attaches to has not yet ben generated.

**Comment by tpluscode** [comment]
There is only one relation layer but set to "Any span"

**Comment by reckart** [comment]
That would also explain it because the system of course won't find a particular layer for "any span" ;)

**Comment by tpluscode** [comment]
Import from JSON did work though. As you said, because it contains additional information?

**Comment by reckart** [comment]
Issue moved here: https://github.com/inception-project/inception/issues/4988
