### ISSUE TITLE
Unable to Import Search Project 

### ISSUE THREAD

**Issue by naveen2507** [inception-project/inception#523]
**Describe the bug**
Unable to import project : 
`integrity constraint violation: NOT NULL check constraint; SYS_CT_10505 table: KNOWLEDGEBASE column: PROPERTYLABELIRI`

**To Reproduce**
1. Go to Projetct
2. Click on Import Project
3. Try to import project 
[Search+Example.zip](https://github.com/inception-project/inception/files/2396957/Search%2BExample.zip)

**Expected behavior**
Import should work

**Please complete the following information:**
 - Version and build ID: [Technische Universität Darmstadt -- Computer Science Department -- INCEpTION 𝜶 -- 0.6.0-SNAPSHOT (2018-09-19 11:53:41, build ac8b660d22b5f5c1b1b33a519f1c6f9b83de149d)]
 - OS: [ Linux]
 - Browser: [chrome]

**Comment by naveen2507** [comment]
Here is the stackstrace of the error: 
`de.tudarmstadt.ukp.clarin.webanno.api.export.ProjectExportException: Project import failed
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl.importProject(ProjectExportServiceImpl.java:273) ~[webanno-api-dao-3.5.0-beta-3.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl$$FastClassBySpringCGLIB$$3d43e16f.invoke(<generated>) ~[webanno-api-dao-3.5.0-beta-3.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]`
......
`Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:149) ~[hibernate-core-5.3.2.Final.jar:5.3.2.Final]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:157) ~[hibernate-core-5.3.2.Final.jar:5.3.2.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1514) ~[hibernate-core-5.3.2.Final.jar:5.3.2.Final]
	at org.hibernate.query.Query.getResultList(Query.java:135) ~[hibernate-core-5.3.2.Final.jar:5.3.2.Final]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.AnnotationSchemaServiceImpl.listAnnotationFeature(AnnotationSchemaServiceImpl.java:571) ~[webanno-api-dao-3.5.0-beta-3.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.AnnotationSchemaServiceImpl$$FastClassBySpringCGLIB$$c4446552.invoke(<generated>) ~[webanno-api-dao-3.5.0-beta-3.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.AnnotationSchemaServiceImpl$$EnhancerBySpringCGLIB$$90b9a19c.listAnnotationFeature(<generated>) ~[webanno-api-dao-3.5.0-beta-3.jar:?]
	at de.tudarmstadt.ukp.inception.kb.exporter.KnowledgeBaseExporter.importData(KnowledgeBaseExporter.java:191) ~[inception-kb-0.6.0-SNAPSHOT.jar:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl.importProject(ProjectExportServiceImpl.java:259) ~[webanno-api-dao-3.5.0-beta-3.jar:?]
	... 180 more
`
....
`Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10505 table: KNOWLEDGEBASE column: PROPERTYLABELIRI
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at sun.reflect.GeneratedMethodAccessor480.invoke(Unknown Source) ~[?:?]
`

**Comment by naveen2507** [comment]
@MdeBoer95 Can you look into this? We need to fix this before we do something on #8 - Example project for in-project search #9

**Comment by reckart** [comment]
The importer needs to be changed such that it sets some default IRI for the new IRI fields because older exported projects will not include the IRIs. In fact, I would recommend that a default IRI is used for all IRIs if no value is included in the imported project. I would suggest to use the IRIs from the OWL profile as defaults.

**Comment by naveen2507** [comment]
We don't have any planned release for 0.5.2. You can go ahead with master

**Comment by reckart** [comment]
Unless there are technical reasons which make it infeasible, I would generally recommend to implement bugfixes always on the maintenance branch - even if no concrete new release of that branch is planned, we could always have one if for some reason the next major release gets delayed.
