### ISSUE TITLE
Cannot import documents where filename contains multi-byte character

### ISSUE THREAD

**Issue by mbugert** [inception-project/inception#680]
**Describe the bug**
Importing a document where the filename contains a multi-byte character yields
`Error: org.hibernate.exception.GenericJDBCException: could not extract ResultSet`

**To Reproduce**
1. Import file named `INCEpTION 𝜶 - Projects Settings.txt`

**Expected behavior**
Import succeeds.

**Please complete the following information:**
 - Version and build ID: 0.6.2 (2018-11-12 15:17:55, build a125fe72aeee207568c5c1da32b702e9b14d3f69) 
 - OS: Ubuntu 18.04
 - Browser: FF 63

**Comment by reckart** [comment]
What kind of DB are you using?

**Comment by mbugert** [comment]
Whatever you are using on your production server.

**Comment by reckart** [comment]
Works locally for me. Looks like a configuration problem on the server:

```
2018-11-21 14:50:12 WARN [rec] SqlExceptionHelper - SQL Error: 1267, SQLState: HY000
2018-11-21 14:50:12 ERROR [rec] SqlExceptionHelper - Illegal mix of collations (utf8_bin,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
2018-11-21 14:50:12 ERROR [rec] ProjectPage - Error: org.hibernate.exception.GenericJDBCException: could not extract ResultSet
javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not extract ResultSet
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1514) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1553) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.DocumentServiceImpl.existsSourceDocument(DocumentServiceImpl.java:236) ~[webanno-api-dao-3.5.0-beta-9.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.DocumentServiceImpl$$FastClassBySpringCGLIB$$7e8e7e07.invoke(<generated>) ~[webanno-api-dao-3.5.0-beta-9.jar!/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.1.RELEASE.jar!/:5.1.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.1.1.RELEASE.jar!/:5.1.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.1.RELEASE.jar!/:5.1.1.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.1.RELEASE.jar!/:5.1.1.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.1.RELEASE.jar!/:5.1.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.1.RELEASE.jar!/:5.1.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.1.RELEASE.jar!/:5.1.1.RELEASE]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.DocumentServiceImpl$$EnhancerBySpringCGLIB$$c97f6688.existsSourceDocument(<generated>) ~[webanno-api-dao-3.5.0-beta-9.jar!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:522) ~[wicket-ioc-8.1.0.jar!/:8.1.0]
	at com.sun.proxy.$Proxy179.existsSourceDocument(Unknown Source) ~[?:?]
	at de.tudarmstadt.ukp.clarin.webanno.ui.project.documents.ImportDocumentsPanel.actionImport(ImportDocumentsPanel.java:119) ~[webanno-ui-project-3.5.0-beta-9.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.support.lambda.LambdaAjaxButton.onSubmit(LambdaAjaxButton.java:52) [webanno-support-3.5.0-beta-9.jar!/:?]
	at org.apache.wicket.ajax.markup.html.form.AjaxButton$1.onSubmit(AjaxButton.java:113) [wicket-core-8.1.0.jar!/:8.1.0]
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior$AjaxFormSubmitter.onSubmit(AjaxFormSubmitBehavior.java:223) [wicket-core-8.1.0.jar!/:8.1.0]
	at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1271) [wicket-core-8.1.0.jar!/:8.1.0]
	at org.apache.wicket.markup.html.form.Form.process(Form.java:964) [wicket-core-8.1.0.jar!/:8.1.0]
	at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:788) [wicket-core-8.1.0.jar!/:8.1.0]
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior.onEvent(AjaxFormSubmitBehavior.java:176) [wicket-core-8.1.0.jar!/:8.1.0]
```

**Comment by jcklie** [comment]
I changed the configuration of the blinky mysql, but the error still is there. I checked that the collate is utf8mb4 in the mysql as it should. 

@reckart  What does 

` SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';`
return you?

On blinky it is

```
MariaDB [(none)]> SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';
+--------------------------+--------------------+
| Variable_name            | Value              |
+--------------------------+--------------------+
| character_set_client     | utf8mb4            |
| character_set_connection | utf8mb4            |
| character_set_database   | utf8mb4            |
| character_set_filesystem | binary             |
| character_set_results    | utf8mb4            |
| character_set_server     | utf8mb4            |
| character_set_system     | utf8               |
| collation_connection     | utf8mb4_general_ci |
| collation_database       | utf8mb4_general_ci |
| collation_server         | utf8mb4_general_ci |
+--------------------------+--------------------+
10 rows in set (0.00 sec)
```

as it should be:

**Comment by reckart** [comment]
You mean on my totally messed up development machine? For your entertainment:

```
+--------------------------+-------------------+
| Variable_name            | Value             |
+--------------------------+-------------------+
| character_set_client     | utf8              |
| character_set_connection | utf8              |
| character_set_database   | latin1            |
| character_set_filesystem | binary            |
| character_set_results    | utf8              |
| character_set_server     | latin1            |
| character_set_system     | utf8              |
| collation_connection     | utf8_general_ci   |
| collation_database       | latin1_swedish_ci |
| collation_server         | latin1_swedish_ci |
+--------------------------+-------------------+
```

**Comment by reckart** [comment]
Here also from the WebAnno server (which I don't know if it exhibits this issue or not):

```
+--------------------------+-------------------+
| Variable_name            | Value             |
+--------------------------+-------------------+
| character_set_client     | latin1            |
| character_set_connection | latin1            |
| character_set_database   | utf8              |
| character_set_filesystem | binary            |
| character_set_results    | latin1            |
| character_set_server     | utf8              |
| character_set_system     | utf8              |
| collation_connection     | latin1_swedish_ci |
| collation_database       | utf8_general_ci   |
| collation_server         | utf8_general_ci   |
+--------------------------+-------------------+
```

**Comment by reckart** [comment]
Might be worth mentioning that I recently went through my local dev INCEpTION DB and manually changed the collation in all tables to `utf8_bin` and the encoding to `utf8` because I was having some kind of issue I don't remember.

**Comment by jcklie** [comment]
I changed the database config to utf and utf_bin, now I get

```
Caused by: org.hibernate.exception.DataException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:52) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:178) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.dialect.identity.GetGeneratedKeysDelegate.executeAndExtract(GetGeneratedKeysDelegate.java:57) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:42) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3072) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3663) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:81) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:645) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:282) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:263) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:317) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:359) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:292) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:200) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:131) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:192) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:135) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:62) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:800) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
	... 128 more
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect string value: '\xF0\x9D\x9C\xB6 -...' for column 'name' at row 1
```

I think we should change the data type for text to utf8mb4, like the internet suggests (e.g.https://mathiasbynens.be/notes/mysql-utf8mb4 ) . I therefore propose to close this issue and open a new one talking about the refactoring.

**Comment by reckart** [comment]
Fine by me.

**Comment by reckart** [comment]
@jcklie according to https://www.eversql.com/mysql-utf8-vs-utf8mb4-whats-the-difference-between-utf8-and-utf8mb4/ the index limitation is no longer a problem with modern MySQL DBs:

> The 768 byte limit is specific to earlier releases of MySQL. In 5.7 the default row+table format is DYNAMIC/BARRACUDA and no longer has this issue.

So if we update the documentation and make MySQL 5.7 or higher a prerequisite, then we probably don't have to migrate anything. We could add some advice for people wanting to migrate their MySQL setup from `utf8` to `utf8mb4` - basically what we did in order to migrate our server...

**Comment by reckart** [comment]
So in order to check if the DB is does not have the index limitation:

> It is easy to identify the file format used by a given table. The table uses the Antelope file format if the row format reported by SHOW TABLE STATUS is either Compact or Redundant. The table uses the Barracuda file format if the row format reported by SHOW TABLE STATUS is either Compressed or Dynamic.

So if "dynamic" is shown for every table, it should probably be save to change the encoding.

**Comment by reckart** [comment]
I have changed all our server DBs back to encoding utf8 and collation utf8-bin because otherwise creating new tables with a primary key `VARCHAR(255)` (like the users table or the instance_id table) fails with this exception:

```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.48.jar!/:5.1.48]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.48.jar!/:5.1.48]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.48.jar!/:5.1.48]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[mysql-connector-java-5.1.48.jar!/:5.1.48]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[mysql-connector-java-5.1.48.jar!/:5.1.48]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[mysql-connector-java-5.1.48.jar!/:5.1.48]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[mysql-connector-java-5.1.48.jar!/:5.1.48]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[mysql-connector-java-5.1.48.jar!/:5.1.48]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2439) ~[mysql-connector-java-5.1.48.jar!/:5.1.48]
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:829) ~[mysql-connector-java-5.1.48.jar!/:5.1.48]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:729) ~[mysql-connector-java-5.1.48.jar!/:5.1.48]
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264) ~[commons-dbcp-1.4.jar!/:1.4]
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264) ~[commons-dbcp-1.4.jar!/:1.4]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:307) ~[liquibase-core-3.5.5.jar!/:?]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55) ~[liquibase-core-3.5.5.jar!/:?]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:113) ~[liquibase-core-3.5.5.jar!/:?]
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1277) ~[liquibase-core-3.5.5.jar!/:?]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1259) ~[liquibase-core-3.5.5.jar!/:?]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:582) ~[liquibase-core-3.5.5.jar!/:?]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51) ~[liquibase-core-3.5.5.jar!/:?]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79) ~[liquibase-core-3.5.5.jar!/:?]
	at liquibase.Liquibase.update(Liquibase.java:214) ~[liquibase-core-3.5.5.jar!/:?]
	at liquibase.Liquibase.update(Liquibase.java:192) ~[liquibase-core-3.5.5.jar!/:?]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:431) ~[liquibase-core-3.5.5.jar!/:?]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388) ~[liquibase-core-3.5.5.jar!/:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	... 25 more
```

In order to make these work with utf8mb4, we'd have to reduce the primary key varchar size to max. 191.

**Comment by jcklie** [comment]
I read somehwere that you could activate `innodb_large_prefix` to circumvent this error.

**Comment by jcklie** [comment]
Wont fix, it requires a DB server config change, not directly INCEpTION code related. We need to update the documentation.

**Comment by reckart** [comment]
@jcklie does the new DB config with utf8mb4 now resolve this issue?

**Comment by jcklie** [comment]
Works for me on blinky stable.
