### ISSUE TITLE
Wicket `@SpringBean` injection generates illegal access warning on recent JDKs

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#780]
**Describe the bug**
Wicket `@SpringBean` injection generates illegal access warning on recent JDKs.

**To Reproduce**
1. Add `--illegal-access=debug` to the VM arguments
2. Run INCEpTION on a recent JDK (9 or higher)
3. Access any page which uses bean injection, e.g. the annotation page
4. See message in log
```
WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$1 (file:.../cglib-3.2.6.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
	at net.sf.cglib.core.ReflectUtils$1.run(ReflectUtils.java:61)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at net.sf.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:52)
	at net.sf.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:243)
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:174)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:153)
	at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73)
	at org.apache.wicket.proxy.LazyInitProxyFactory.createProxy(LazyInitProxyFactory.java:183)
	at org.apache.wicket.spring.injection.annot.AnnotProxyFieldValueFactory.getFieldValue(AnnotProxyFieldValueFactory.java:166)
	at org.apache.wicket.injection.Injector.inject(Injector.java:111)
	at org.apache.wicket.spring.injection.annot.SpringComponentInjector.inject(SpringComponentInjector.java:124)
	at org.apache.wicket.spring.injection.annot.SpringComponentInjector.onInstantiation(SpringComponentInjector.java:130)
	at org.apache.wicket.application.ComponentInstantiationListenerCollection$1.notify(ComponentInstantiationListenerCollection.java:38)
	at org.apache.wicket.application.ComponentInstantiationListenerCollection$1.notify(ComponentInstantiationListenerCollection.java:34)
	at org.apache.wicket.util.listener.ListenerCollection.notify(ListenerCollection.java:80)
	at org.apache.wicket.application.ComponentInstantiationListenerCollection.onInstantiation(ComponentInstantiationListenerCollection.java:33)
	at org.apache.wicket.Component.<init>(Component.java:679)
	at org.apache.wicket.MarkupContainer.<init>(MarkupContainer.java:178)
	at org.apache.wicket.markup.html.WebMarkupContainer.<init>(WebMarkupContainer.java:53)
	at org.apache.wicket.markup.html.WebMarkupContainer.<init>(WebMarkupContainer.java:45)
	at org.apache.wicket.markup.html.panel.Panel.<init>(Panel.java:67)
```

**Expected behavior**
No warning.

**Please complete the following information:**
 - Version and build ID: 758647ee1a3bb43eac7ff85067417b75e09344d9

**Comment by reckart** [comment]
Problem seems to happen specifically when injecting beans as class, not via interface, e.g.  it happens for `de.tudarmstadt.ukp.inception.kb.config.KnowledgeBaseProperties` but not for most other services which come with an interface.
