### ISSUE TITLE
Error Page when saving Concept Feature traits

### ISSUE THREAD

**Issue by MdeBoer95** [inception-project/inception#833]
**Describe the bug**
When the save button for the concept feature traits is clicked a NullPointerException is thrown and the ErrorPage is shown.

**To Reproduce**
1. Go to Layer configurations and select NamedEntity layer. Try to save configurations for the identifier feature.
2. See error

**Expected behavior**
The feature traits should be saved without any error

**Please complete the following information:**
 - Version and build ID: [ Technische Universität Darmstadt -- Computer Science Department -- INCEpTION 𝜶 -- 0.7.0-SNAPSHOT (, build )  ]
 - OS: [Linux]
 - Browser: [chrome]

**Comment by MdeBoer95** [comment]
https://github.com/inception-project/inception/blob/64811fa301e3838b6e828166e078c8ca55079ce3/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureTraitsEditor.java#L69-L94

@reckart When I look at it in the debugger the model object of ```feature```(l.69) is ```null``` in ```onSubmit()``` but not when when the ConceptFeatureTraitsEditor is created. So the value is set properly but "suddenly" ```null``` when  ```onSubmit()``` is called.
Any idea why that happens?

**Comment by reckart** [comment]
@MdeBoer95 no idea. These fields can be marked with `final` and the compiler doesn't complain - so if they start out with a non-null value, that value should never change. Try making the fields final and add a `Validate.notNull(...)` to ensure the field doesn't start out non-null.

**Comment by MdeBoer95** [comment]
Still not sure why exactly it happens but I have a workaround in PR #835

**Comment by reckart** [comment]
I have just hit this problem with a `LinkFeature` - so it is a general problem, not one that is to be fixed in the ConceptFeature only.

```
java.lang.NullPointerException: null
	at de.tudarmstadt.ukp.clarin.webanno.api.annotation.feature.SlotFeatureSupport.writeTraits(SlotFeatureSupport.java:284) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.annotation.feature.editor.LinkFeatureTraitsEditor.writeTraits(LinkFeatureTraitsEditor.java:169) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.annotation.feature.editor.LinkFeatureTraitsEditor.access$0(LinkFeatureTraitsEditor.java:161) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.annotation.feature.editor.LinkFeatureTraitsEditor$1.onSubmit(LinkFeatureTraitsEditor.java:84) ~[classes/:?]
```

**Comment by reckart** [comment]
Bug was apparently introduced in https://github.com/webanno/webanno/commit/bffdb6b7ccaeacbae36af4e33208c496497356b6 when the `FeatureDetailForm.actionSave()` was changed to clear the currently selected feature. 

Problem needs to be fixed upstream.
