### ISSUE TITLE
Error Importing Layers

### ISSUE THREAD

**Issue by rfinz** [inception-project/inception#998]
Received an error after attempting to import layers in one Inception project from a uima typesystem created in another inception project. Here's the relevant part of the error 
```
2019-03-01 00:01:56 ERROR [admin] ApplicationPageBase - admin: Error importing layers: ResourceInitializationException: Undefined type "de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity", referenced in feature "target" declared on type "de.tudarmstadt.ukp.inception.api.kb.type.FactObjectLink". (Descriptor: <unknown>)
2019-03-01 00:02:25 ERROR [admin] ProjectLayersPanel - Error importing layers
org.apache.uima.resource.ResourceInitializationException: Undefined type "de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity", referenced in feature "target" declared on type "de.tudarmstadt.ukp.inception.api.kb.type.FactObjectLink". (Descriptor: <unknown>)
	at org.apache.uima.util.CasCreationUtils.setupTypeSystem(CasCreationUtils.java:816) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.util.CasCreationUtils.doCreateCas(CasCreationUtils.java:598) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.util.CasCreationUtils.createCas(CasCreationUtils.java:357) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.util.CasCreationUtils.createCas(CasCreationUtils.java:308) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at de.tudarmstadt.ukp.clarin.webanno.xmi.TypeSystemAnalysis.analyzeTypeSystem(TypeSystemAnalysis.java:113) ~[webanno-io-xmi-3.5.2.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.xmi.TypeSystemAnalysis.of(TypeSystemAnalysis.java:104) ~[webanno-io-xmi-3.5.2.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.ui.project.layers.ProjectLayersPanel$ImportLayerForm.importUimaTypeSystemFile(ProjectLayersPanel.java:305) ~[webanno-ui-project-3.5.2.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.ui.project.layers.ProjectLayersPanel$ImportLayerForm.actionImport(ProjectLayersPanel.java:283) ~[webanno-ui-project-3.5.2.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.support.lambda.LambdaAjaxButton.onSubmit(LambdaAjaxButton.java:52) [webanno-support-3.5.2.jar!/:?]
	at org.apache.wicket.ajax.markup.html.form.AjaxButton$1.onSubmit(AjaxButton.java:113) [wicket-core-8.1.0.jar!/:8.1.0]
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior$AjaxFormSubmitter.onSubmit(AjaxFormSubmitBehavior.java:223) [wicket-core-8.1.0.jar!/:8.1.0]
```
I'm attaching the typesystem that threw the error, though I believe other typesystems will do it as well.

[typesytem.txt](https://github.com/inception-project/inception/files/2918113/typesytem.txt)

**Comment by reckart** [comment]
@rfinz did you export that TS from INCEpTION or does it come from somewhere else?

**Comment by rfinz** [comment]
I exported it from INCEpTION

**Comment by reckart** [comment]
@rfinz ok, thanks. I need to think a bit on how to best fix this problem. Basically there are these options:

* include all defined layers in the UIMA TS export, even the built-in DKPro Core types
* somehow merge the built-in types during import / type system analysis to complete the TS

I tend towards the first option for the moment...

**Comment by reckart** [comment]
Upstream issue fixed. Will be included in next INCEpTION release.
